modern-agile-team/modern-kit

.changeset/good-seals-remain.md
docs/docs/react/hooks/usePreservedState.mdx
packages/react/src/hooks/index.ts
packages/react/src/hooks/useAsyncPreservedCallback/index.ts
packages/react/src/hooks/usePreservedCallback/index.ts
packages/react/src/hooks/usePreservedState/index.ts
packages/react/src/hooks/usePreservedState/usePreservedState.spec.ts

비교 함수(comparator)를 통해 true를 반환하면 상태를 유지하고, false를 반환하면 상태를 변경하는 커스텀 훅인 usePreservedState를 추가합니다.
만약 상태가 유지된다면 참조까지 유지됩니다.
comparator는 인자로 넣지 않는다면 기본적으로 `@modern-kit/utils`의 [deepEqual](https://modern-agile-team.github.io/modern-kit/docs/utils/common/deepEqual)이 활용됩니다.

feat(react): usePreservedState 추가

---

packages/react/src/components/SwitchCase/SwitchCase.test.tsx
packages/react/src/components/SwitchCase/index.tsx
packages/react/src/components/When/When.spec.tsx
packages/react/src/components/When/index.tsx
packages/react/src/components/index.ts

feat(#100): SwitchCase 컴포넌트 추가

---

docs/docs/react/hooks/useDebounce.mdx

이전에 논의한 바와 같이 useBlockPromiseMultipleClick 훅에서 useDebounce와의 비교를 언급하였기에 두 훅에 대해 더 쉽게 이해할 수 있도록 누락되어있던 useDebounce 함수의 사용 예시를 추가했습니다. 
더 좋은 의견이 있으시다면 편하게 말씀주시면 감사드리겠습니다. :)
https://github.com/modern-agile-team/modern-kit/assets/26050574/842774f6-af09-4f23-b191-0d299b609e5c
- [O] All tests pass.
- [O] All type checks pass.
- [O] I have read the Contributing Guide document.

docs(hooks): useDebounce 훅의 문서 내 예시 추가 완료

---

.github/workflows/pull-request.yml

git workflow document build  조건식 제거
초기 의도에는 추가 문서 작업을 고려하지 않고 `dependabot`을 통해 의존성 변경 시에만 일반 build(test, typecheck포함) + build:docs를 함께 진행했는데, 일반적인 작업 시에도 추가/수정 문서 작업이 포함될 수 있기 때문에 build:docs가 정상 동작하는지 확인 할 수 있어야 합니다.
따라서, pull request  workflow에서 해당 조건식을 제거합니다.
해당 작업에 영감을 주셔서 감사합니다! @Sangminnn 

chore: git workflow document build  조건식 제거

---

.changeset/seven-pants-eat.md
.eslintrc.cjs
docs/docs/react/components/When.mdx

docs: When 컴포넌트 문서 수정

---

docs/docs/utils/common/parseJson.md
packages/utils/src/common/parseJson/index.ts
packages/utils/src/common/parseJson/parseJson.spec.ts

일반적으로 JSON.parse를 사용하는 경우 일부 input값에 대해서는 에러를 반환합니다. 
이 함수를 사용하면 에러를 반환하는 상황에서 null을 반환하여 예상치 못한 에러상황을 방지할 수 있을 것으로 기대합니다!
편하게 의견주시면 감사드리겠습니다 :)
- [O] All tests pass.
- [O] All type checks pass.
- [O] I have read the Contributing Guide document.

feat(utils): parseJson 함수 추가 완료

---

.changeset/sour-hats-smash.md
docs/docs/utils/object/deleteEmptyProperties.md
docs/docs/utils/validator/isArray.md
packages/utils/src/object/deleteFalsyProperties/deleteFalsyProperties.spec.ts
packages/utils/src/object/deleteFalsyProperties/index.ts
packages/utils/src/validator/index.ts
packages/utils/src/validator/isArray/index.ts
packages/utils/src/validator/isArray/isArray.spec.ts

deleteEmptyProperties 개선 및 isArray 유틸 함수 추가

fix: deleteEmptyProperties 개선

---

.changeset/wicked-needles-cheat.md
docs/docs/utils/clipboard/clipboardFallbackTextCopy.md
docs/docs/utils/clipboard/clipboardImageCopy.md
docs/docs/utils/clipboard/clipboardTextCopy.md
packages/utils/src/clipboard/clipboardFallbackTextCopy/index.ts
packages/utils/src/clipboard/clipboardImageCopy/index.ts
packages/utils/src/clipboard/clipboardTextCopy/index.ts
packages/utils/src/clipboard/index.ts
packages/utils/src/index.ts
packages/utils/src/storage/index.ts
packages/utils/vitest.config.ts

issue: #122 
Clipboard 관련 유틸 함수 및 문서를 추가하였습니다. (clipboardFallbackTextCopy, clipboardTextCopy, clipboardImageCopy)
`Clipboard API`를 지원하는 브라우저인 경우 `Clipboard API`를 활용할 수 있게 했습니다. 
`Clipboard API`를 지원하지 않는 브라우저 + HTTPS 환경이 아니라면 호출하는 fallback 함수인 `clipboardFallbackTextCopy`를 구현하였습니다.
`web.dev` 가이드 문서를 참조하였습니다.
[텍스트 복사](https://web.dev/patterns/clipboard/copy-text?hl=ko)
[이미지 복사](https://web.dev/patterns/clipboard/copy-images?hl=ko)
[클립보드 액세스 차단 해제 ](https://web.dev/articles/async-clipboard?hl=ko)

feat(utils): clipboard 유틸 함수 추가 (clipboardFallbackTextCopy, clipboardTextCopy, clipboardImageCopy)

---

.changeset/swift-papayas-march.md
docs/docs/utils/clipboard/clipboardImageCopy.md
docs/docs/utils/file/convertImageToBase64.md
docs/docs/utils/file/getMIMETypeFromResponse.md
packages/utils/src/clipboard/clipboardImageCopy/index.ts
packages/utils/src/file/convertImageToBase64/index.ts
packages/utils/src/file/getMIMEType/index.ts
packages/utils/src/file/getMIMETypeFromResponse/index.ts
packages/utils/src/file/index.ts

이미지를 Base64 형태로 변경해주는 `converImageToBase64` 함수를 추가했습니다.
`clipboardImageCopy` 함수에서 `webp`, `jp(e)g`의 경우 Clipboard 저장이 제한적입니다. 
이를 저장하려면 `png` 형태로 변경해서 저장을 해야됩니다. 이를 위해 `toPng` 옵션을 추가하고, toPng가 `true`일 경우 `converImageToBase64`를 활용해 base64의 png 포맷으로 변경 후에 클립보드에 저장합니다.

feat(utils): converImageToBase64 함수 추가

---

.changeset/rich-hairs-push.md
docs/docs/react/hooks/useKeyDown.mdx
packages/react/src/hooks/index.ts
packages/react/src/hooks/useKeydown/index.ts
packages/react/src/hooks/useKeydown/useKeydown.spec.tsx

#141 
원하는 요소에 `ref`를 넘겨주고, ref를 받은 요소가 포커싱 된 상태에서 `keydown` 이벤트 발생시 keyDownCallbackMap props로 지정한 특정 `KeyboardEvent.key`에 대한 콜백 함수가 호출되는 커스텀 훅입니다. `allKeydownCallback`를 통해 모든 KeyboardEvent.key에대한 함수 호출도 가능합니다.
autoFocus를 통해 자동 포커싱도 가능합니다.

feat(react): useKeyDown 커스텀 훅 추가

---

.changeset/happy-days-rescue.md
docs/docs/utils/common/deepCopy.md
packages/utils/src/common/deepCopy/deepCopy.spec.ts
packages/utils/src/common/deepCopy/index.ts

- 자신을 참조하는 데이터를 deepCopy했을 때 maximum call stack 이슈가 발생하던 것을 해결했습니다.
- `Date`, `Regex` 타입의 간단한 깊은 복사 테스트 코드를 추가했습니다.
- 복사된 값을 할당하는 변수명이 동사로 되어있어 수정했습니다.

fix(utils): deepCopy 순환참조 대응 및 Date, Regex 테스트 코드 추가

---

.changeset/tall-steaks-melt.md
docs/docs/react/hooks/useDoumentTitle.mdx
packages/react/src/hooks/index.ts
packages/react/src/hooks/useDocumentTitle/index.ts
packages/react/src/hooks/useDocumentTitle/useDoucmentTitle.spec.ts

Issue: https://github.com/modern-agile-team/modern-kit/issues/147
SEO와 관계 없이 document.title을 동적으로 변경하는 커스텀 훅 작업 (테스트 코드 + 문서 포함)

feat(react): useDocumentTitle 커스텀 훅 추가

---

packages/utils/src/common/deepEqual/deepEqual.spec.ts
packages/utils/src/common/deepEqual/index.ts

- deepEqual NaN 비교 추가
- Set 요소 순서까지 같아야 동일한 값임을 나타내는 테스트 케이스 추가
- Set 요소의 순서가 다르더라도 요소 값이 같으면 같다고 판단할지는 @ssi02014 님께서 정의해 주시면 좋을 것 같습니다.
```js
if (
typeof source === 'number' &&
typeof target === 'number' &&
isNaN(source) &&
isNaN(target)
) {
return true;
}
```

feat(utils): NaN 검증 추가 및 Set 테스트 추가

---

.changeset/slimy-coats-obey.md
packages/utils/src/common/delay/delay.spec.ts
packages/utils/src/common/delay/index.ts

- delay 함수 인자로 받는 `time`에 대한 NaN, 음수 검증을 추가했습니다.
- 예외에 대한 처리가 애매한데 좋은 방법이 있을까요? 현재는 `new Error("Invalid time value")`를 던지고 있는데 더 적합한 방식이 있으면 의견 부탁드립니다!

feat(utils): delay 인자 음수, NaN 검증 추가

---

docs/docs/react/components/OutsideClick.mdx
packages/react/src/components/OutsideClick/ClickOutside.spec.tsx
packages/react/src/components/OutsideClick/OutsideClick.spec.tsx
packages/react/src/components/OutsideClick/index.tsx
packages/react/src/components/index.ts
packages/react/src/hooks/useOnClickOutside/index.ts

```jsx
const { ref } = useOnClickOutside(callback);
return <div ref={ref}>inside</div>;
```
```jsx
<OutsideClick callback={() => console.log('outside clicked!')}>
<div>something</div>
</OutsideClick>
```
<br/>
A component that declaratively handles the functionality of `useOnClickOutside`.
If you click outside the component wrapped in `OutsideClick`, `callback` is executed.
```jsx
<OutsideClick callback={callback}>{children}</OutsideClick>
```
Assign an `ElementType` to `<OutsideClick>`.
Use `HTMLAttributes` as needed.
```jsx
function Component() {
return (
<OutsideClick<'input'>
as='input'
callback={() => {
console.log('outside clicked!');
}}
/>
);
}
```
- Documentation completed. (73532b4078cddbbd2185f78a3a789c820df9365b)
- Test code completed. (92e652ae8dab2278a8a8d419d945df09d7f26f55) …

feat(react): OutsideClick 컴포넌트 구현

---

.changeset/stale-mangos-suffer.md
docs/docs/utils/style/rem.md
docs/docs/utils/validator/hasProperty.md
packages/react/src/hooks/useHover/useHover.spec.tsx
packages/utils/src/index.ts
packages/utils/src/style/index.ts
packages/utils/src/style/rem/index.ts
packages/utils/src/style/rem/rem.spec.ts

`Root 요소(html)`의 `fontSize`를 기반으로 `pixel` 값을 `rem` 형태로 변환해주는 유틸 함수입니다.
`css in js` 환경 등에서 유용하게 활용할 수 있습니다.

feat(utils): rem 신규 유틸 함수 추가

---

.changeset/olive-flies-hope.md
docs/docs/react/hooks/useInterval.mdx
packages/react/src/hooks/useInterval/index.ts
packages/react/src/hooks/useInterval/useInterval.spec.tsx

useInterval은 사용자가 직접 중간에 Interval을 멈추거나, 다시 동작시키거나 하는 니즈가 있을 수 있기때문에 이를 조절할 수 있게 명시적인 `enabled` 옵션을 추가합니다. 기존 버전과의 호환성을 위해 인터페이스를 많이 수정하기보다 options라는 3번째 인자를 추가하였습니다.
그 외 아래와 같은 작업이 진행됐습니다.
- Test 코드가 개선되었습니다. renderHook만으로 모든 기능 테스트가 가능하므로 컴포넌트를 통한 테스트 코드는 제거하였습니다.
- 실제 실습 예제를 추가하면서 문서를 보완하였습니다.

fix(react): useInterval enabled 속성 추가

---

.eslintrc.cjs
package.json
scripts/coauthor.js

최근 공동 작업자를 추가하는 작업을 하면서 각 유저의 `Github Email` 확인에 있어 불편함을 느꼈습니다.
따라서, Github UserName을 기반으로 Github API를 활용해 `no-reply` 형태의 이메일을 수집 후,
이를 활용해 `co-author 메시지`를 생성하는 함수를 작성하였습니다.
터미널에서 아래와 같이 실행 할 수 있습니다.
```shell
yarn coauthor {userName} {userName} {userName} ...
```
```
ex) yarn coauthor ssi02014 Sangminnn
Co-authored-by: Gromit (전민재) <64779472+ssi02014@users.noreply.github.com>
Co-authored-by: Sangminnn <26050574+Sangminnn@users.noreply.github.com>
```
위와 같이 생성된 co-author message로 손쉽게 공동 작업자를 추가 할 수 있습니다.
- [여러 작성자와 커밋 만들기](https://docs.github.com/ko/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors)
- [coauthors](https://github.com/coauthors/coauthors)
[Contributing …

feat: coauthor 함수 추가

---

.changeset/loud-zebras-shave.md
docs/docs/utils/array/chunk.md
packages/types/src/Integer/index.ts
packages/types/src/NaturalNumber/index.ts
packages/types/src/WholeNumber/index.ts
packages/types/src/index.ts
packages/utils/src/array/chunk/chunk.spec.ts
packages/utils/src/array/chunk/index.ts
packages/utils/src/array/index.ts

Issue: #158 
<br/>
- `chunk` 메서드를 구현했습니다. (d81502106bc4c56e552ae85197c29a076bcdf46f)
- 컴파일과정에서 2번째 매개변수에 자연수만 할당하고 싶어 `Integer`, `NaturalNumber` 타입을 함께 구현했습니다. (8aa958e99299df8c71e7451708ecb9dd7103545b)
<br/>
close #158 

feat(utils): chunk 유틸 함수 구현

---

.changeset/fair-windows-jump.md
docs/docs/react/hooks/useNetwork.mdx
packages/react/src/hooks/index.ts
packages/react/src/hooks/useNetwork/index.ts
packages/react/src/hooks/useNetwork/useNetwork.spec.tsx

Issue: https://github.com/modern-agile-team/modern-kit/issues/181
신규 `useNetwork` 훅을 추가합니다.
해당 훅은 React에서 제공하는 `useSyncExternalStore`훅을 통해 브라우저 네트워크 상태를 구독 후 `online 여부(isOnline)`에 대한 값을 반환하는 커스텀 훅입니다.
`onlineCallback`, `offlineCallback` props를 통해 네트워크가 변경됐을 때 특정 함수를 호출 할 수 있습니다.
해당 기능은 사용자가 서비스를 이용하다 갑자기 네트워크가 중단됐을 때 특정 행위를 할 수 있기 때문에 굉장히 강력한 기능입니다.
예를 들어, 아래와 같이 fallback 페이지로 이동시킬 수 있습니다.
```ts
const { isOnline } = useNetwork({
onlineCallback: () => {
// online으로 네트워크가 변경됐을 때 원하는 행위
},
offlineCallback: () => {
navigate('/offline');
},
});
```
https://ko.react.dev/reference/react/useSyncExternalStore#subscribing-to-a-browser-api
위 문서의 나오는 예제를 기반으로 작성됐지만 `onlineCallback`, `offlineCallback` 등의 기능들이 추가됐습니다.
- useSyncExternalStore를 사용함에 따라 react, react-dom의 peerDependency를 `^18` 로 변경합니다. …

feat(react): useNetwork 신규 훅 추가

---

.changeset/unlucky-rules-shop.md
docs/docs/utils/array/contain.md
packages/utils/src/array/contain/contain.spec.ts
packages/utils/src/array/contain/index.ts
packages/utils/src/array/index.ts

Issue: https://github.com/modern-agile-team/modern-kit/issues/196
첫 번째 인자로 넘긴 배열에 특정 요소가 포함되어 있는지 판단하는 유틸 함수입니다.
includes는 `as const`를 활용 했을 때, 타입이 호환되지 않은 요소가 포함되어 있는지 확인 할 때 타입 에러가 발생하는 문제점을 `some` 메서드를 활용해 개선한 함수입니다.
```ts title="typescript"
const arr = [1, 2, 3] as const
arr.includes(4); // '4' 형식의 인수는 '1 | 2 | 3' 형식의 매개 변수에 할당될 수 없습니다.
```
`some` 메서드를 통해 요소가 포함되어 있는지 판단 할 때 기본적으로 `Object.is` 메서드를 활용합니다. 단, 필요 시에 3번째 인자로 `comparator` 함수를 활용 할 수 있습니다.
[Object.is](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Object/is)를 활용한 이유는 `==` 보다는 엄격하게 관리되며, `===`보다 조금 더 개발자가 기대하는 결과를 가져옵니다. 예를 들어 `===`과 비교해서 `NaN`은 같다고 판단하며, `-0과 +0`은 서로 다르다고 판단합니다. 
```ts
-0 === +0 // true
Object.is(-0, +0); // false
NaN === NaN; // false;
Object.is(NaN, NaN); // true …
```

feat(utils): contain 신규 유틸 함수 추가

---

.changeset/eight-colts-press.md
docs/docs/utils/common/delay.md
packages/utils/src/common/delay/delay.spec.ts
packages/utils/src/common/delay/index.ts

delay함수를 개선합니다.
주어진 시간 이후에 특정 함수를 호출 할 수 있게 2번째 인자로 callback 함수를 받아올 수 있게 수정하였습니다.
또한 NaN의 경우와 더불어 Infinite, -Infinite, 소수 등과 같은 예외 케이스를 처리하기 위해 isNaN에서 [Number.isInterger](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger)로 변경하였습니다.

fix(utils): delay 유틸 함수 개선

---

.changeset/cyan-weeks-approve.md
docs/docs/react/components/InView.mdx
docs/docs/react/components/LazyImage.mdx
docs/docs/react/hooks/useIntersectionObserver.mdx
packages/react/src/components/InView/InView.spec.tsx
packages/react/src/components/InView/index.tsx
packages/react/src/components/LazyImage/index.tsx
packages/react/src/hooks/useIntersectionObserver/index.ts
packages/react/src/hooks/useIntersectionObserver/useIntersectionObserver.spec.tsx

useIntersectionObserver를 개선합니다.
기존에는 타겟 요소가 viewport에 노출 될 때만 action 콜백을 호출했지만, `노출 될 때(onIntersectStart)`와 `나갈 때(onIntersectStart)` 모두 대응 할 수 있게 수정하였습니다.
useIntersectionObserver가 수정됨에 따라 InView, LazyImage 컴포넌트도 수정하였습니다.

feat(react): useIntersectionObserver 개선 및 InView, LazyImage 수정

---

.changeset/fresh-worms-melt.md
docs/docs/utils/common/identity.md
docs/docs/utils/object/invert.md
packages/utils/src/common/identity/identity.spec.ts
packages/utils/src/common/identity/index.ts
packages/utils/src/common/index.ts
packages/utils/src/object/index.ts
packages/utils/src/object/invert/index.ts
packages/utils/src/object/invert/invert.spec.ts

Issue: https://github.com/modern-agile-team/modern-kit/issues/193
invert는 객체의 key와 value를 뒤집는 함수입니다.
```ts
const obj = { a: 1, b: 2, c: 3 };
const newObj = invert(obj); // { 1: 'a', 2: 'b', 3: 'c' };
```
만약 키가 동일한게 있다면 뒤에 있는 요소로 덮어씁니다.
```ts
const obj = { a: 1, b: 2, c: 1 };
const newObj = invert(obj); // { 1: 'c', 2: 'b' };
```
2번째 인자로 함수를 넘겨 (`keyTransformer`) 직접 key 핸들링 작업을 할 수 있습니다
```ts
const obj = { a: 1, b: 2, c: 3 };
const newObj = invert(obj, (value) => {
return `test${value}`
}); // { test1: 'a', test2: 'b', test3: 'c' };
```
```ts
const obj = { a: 1, b: [1, 2, 3] };
const newObj = invert(obj, (value) => {
return JSON.stringify(value);
}); // { '1': 'a', '[1,2,3]': 'b' }
```
<br />
identity함수는 인자로 받은 함수를 그대로 반환하는 유틸 함수입니다.
```ts
identity("test"); // "test"
```
[Contributing …

feat(utils): invert, identity 유틸 함수 추가

---

.changeset/wet-actors-drop.md
docs/docs/utils/array/partition.md
packages/utils/src/array/index.ts
packages/utils/src/array/partition/index.ts
packages/utils/src/array/partition/partition.spec.ts

Issue: https://github.com/modern-agile-team/modern-kit/issues/215
첫 번째 인자의 배열을 기준으로 2번째 인자인 `predicate` 함수가 `true를 반환하는 요소들의 모음`과 `false를 반환하는 요소`들의 모음 두 그룹으로 나눈 배열을 반환하는 함수입니다.

feat(utils): partition 유틸 함수 추가

---

docs/docs/utils/object/invert.md
packages/utils/src/object/invert/index.ts
packages/utils/src/object/invert/invert.spec.ts

invert가 조금 더 명확한 타입을 추론하기 위해 타입을 개선하였습니다.
이제 invert함수가 조금 더 명확한 타입을 추론할 수 있습니다.
```ts
// as-is
const obj = {
a: { name: 'foo' },
b: { name: 'bar' },
} as const;
const result = invert(obj, (value) => value.name);
// const result: Record<PropertyKey, any>
```
```ts
// to-be
const obj = {
a: { name: 'foo' },
b: { name: 'bar' },
} as const;
const result = invert(obj, (value) => value.name);
// const result: Record<'foo' | 'bar', 'a' | 'b'>
```
<br />
```ts
// as-is
const obj = { a: 1, b: 2, c: 3 };
const keyTransformer = (value: number): `key_${number}` => `key_${value}`;
const result = invert(obj, keyTransformer);
// const result: Record<PropertyKey, any>
```
```ts
// to-be
const obj = { a: 1, b: 2, c: 3 };
const keyTransformer = (value: number): `key_${number}` => `key_${value}`;
const …
```

fix: invert 명확한 타입 추론을 위한 타입 개선

---

.changeset/shaggy-planes-develop.md
docs/docs/utils/array/uniq.md
packages/utils/src/array/index.ts
packages/utils/src/array/uniq/index.ts
packages/utils/src/array/uniq/uniq.spec.ts

Issue: https://github.com/modern-agile-team/modern-kit/issues/222
`중복 요소를 제외한 배열`을 반환하는 함수입니다.
기본적으로 `원시 값`에 대해서만 중복 요소를 판단하며, 필요 시 2번째 인자인 `iteratee` 함수 결과로 중복 요소임을 판단 할 수 있습니다.
```ts
uniq([1, 2, 3]); // [1, 2, 3] 
uniq([1, 2, 2, 2, 3]); // [1, 2, 3] 
```
```ts
const testArr = [
{ id: 1, name: 'John' },
{ id: 2, name: 'Jane' },
{ id: 1, name: 'John' },
];
uniq(testArr, (item) => item.id === 1);
/*
[
{ id: 1, name: 'John' },
{ id: 2, name: 'Jane' },
];
*/
uniq([1, 2, 2.1, 2.2, 2.3, 3], (item) => Math.floor(item)); // [1, 2, 3]
```

feat(utils): uniq 신규 유틸 함수 추가

---

.changeset/lovely-geese-turn.md
docs/docs/react/hooks/useVhProperty.mdx
packages/react/src/hooks/index.ts
packages/react/src/hooks/useVhProperty/index.ts
packages/react/src/hooks/useVhProperty/useVhProperty.spec.ts

Issue: #148 
iOS환경에서 주소표시줄의 높이로 인해 100vh가 실제 보이는 화면의 높이보다 크게 측정되는 이슈를 해결하기 위해, 아래의 훅을 사용하여 주소표시줄의 높이를 제외한 height를 계산할 수 있도록 css변수를 설정해주는 훅입니다.
(이슈를 가지고간 후로 작업까지 너무 오래걸렸습니다 송구합니다 😂 )
- [O] All tests pass.
- [O] All type checks pass.
- [O] I have read the Contributing Guide document.

feat(react): useVhProperty 훅 추가 완료

---

.changeset/lazy-years-change.md
docs/docs/utils/array/contain.md
docs/docs/utils/array/excludeElements.md
docs/docs/utils/array/partition.md
docs/docs/utils/array/union.md
docs/docs/utils/array/uniq.md
packages/types/src/ArrayWithReadonly/index.ts
packages/types/src/index.ts
packages/utils/src/array/contain/index.ts
packages/utils/src/array/excludeElements/index.ts
packages/utils/src/array/partition/index.ts
packages/utils/src/array/union/index.ts
packages/utils/src/array/union/union.spec.ts
packages/utils/src/array/uniq/index.ts
packages/utils/src/array/uniq/uniq.spec.ts

Issue: https://github.com/modern-agile-team/modern-kit/issues/210
두 배열을 결합 후, `중복 요소를 제외해 고유한 값만을 갖는` 새로운 배열을 반환하는 함수입니다.
기본적으로 `원시 값`에 대해서만 중복 요소를 판단하며, 필요 시 3번째 인자인 `iteratee` 함수 결과로 중복 요소임을 판단 할 수 있습니다.
```ts
union([1, 2, 3, 4], [1, 2, 3, 5]); // [1, 2, 3, 4, 5] 
```
```ts
const arr1 = [
{ id: 1, name: 'john' },
{ id: 2, name: 'jane' },
];
const arr2 = [
{ id: 1, name: 'john' },
{ id: 3, name: 'gromit' },
];
union(arr1, arr2, (item) => item.id);
/*
[
{ id: 1, name: 'john' },
{ id: 2, name: 'jane' },
{ id: 3, name: 'gromit' }
]
*/
```

feat(utils): union 유틸 함수 추가 및 ArrayWithReadonly 유틸 타입 추가

---

.changeset/unlucky-turtles-look.md
docs/docs/react/components/LazyImage.mdx
packages/react/src/components/LazyImage/index.tsx

컴포넌트 내부적으로 스타일을 제어하는 것은 불 필요하기 때문에 LaztImage 컴포넌트 내부 스타일을 제거합니다.

fix(react): LazyImage 내부 스타일 제거

---

.changeset/wise-jeans-provide.md
docs/docs/utils/validator/isInRange.mdx
packages/utils/src/validator/index.ts
packages/utils/src/validator/isInRange/index.ts
packages/utils/src/validator/isInRange/isInRange.spec.ts

Issue: #238 
특정 값이 범위에 속하는지를 검증해주는 함수입니다.
인자로 equalOptions 객체를 받아 해당 각 범위의 양 끝을 포함할지 여부를 설정할 수 있습니다.
equalOptions의 기본값은 js의 slice의 인터페이스와 동일하게 min값은 true, max값은 false로 min값은 포함, max값은 포함하지 않습니다.
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/slice

feat(utils): isInRange 함수 작업 완료

---

.changeset/new-trees-play.md
.changeset/ten-files-push.md
docs/docs/react/hooks/useLocalStorage.mdx
packages/react/src/hooks/index.ts
packages/react/src/hooks/useLocalStorage/index.ts
packages/react/src/hooks/useLocalStorage/useLocalStorage.spec.tsx
packages/react/src/utils/customEventHandler.ts
packages/utils/src/validator/isFunction/index.ts

Issue: https://github.com/modern-agile-team/modern-kit/issues/179
`React v18`부터 지원하는 **[useSyncExternalStore](https://react.dev/reference/react/useSyncExternalStore)** 을 활용해 로컬 스토리지 내의 특정 `key` 데이터를 구독하고, 구독 중인 데이터에 변화가 있을 시 이를 동기화해주는 커스텀 훅입니다.
로컬스토리지에 구독하고자 하는 `key`가 없을 경우 반환할 `initialValue`로 초기값을 설정할 수 있습니다.
또한, `서버 사이드 렌더링(SSR)`의 경우 로컬스토리지가 동작하지 않기 때문에 `initialValue`가 반환됩니다.
```tsx
const { state, setState, removeState } = useLocalStorage({
key: 'test',
initialValue: 'default',
});
```
https://github.com/modern-agile-team/modern-kit/assets/64779472/86d8dd5a-2dfd-4d4c-9ea1-381747b4685f

feat(react): useLocalStorage 신규 훅 추가

---

docs/docs/react/hooks/useLocalStorage.mdx
packages/react/src/hooks/useLocalStorage/index.ts

setState가 useState의 setState와 동일하게 함수로 호출 시에는 state 인자가 최신 데이터를 바라보게끔 수정하였습니다.
직접 JSON.parse 하던 부분을 modern-kit/utils의 `parseJSON`으로 변경합니다.
그 외 타입을 개선합니다

fix: useLocalStorage setState 및 타입 개선

---

.changeset/wet-hats-taste.md
docs/docs/react/hooks/useLocalStorage.mdx
docs/docs/react/hooks/useSessionStorage.mdx
packages/react/src/hooks/index.ts
packages/react/src/hooks/useSessionStorage/index.ts
packages/react/src/hooks/useSessionStorage/useSessionStorage.spec.tsx

Issue: https://github.com/modern-agile-team/modern-kit/issues/240
localStorage: https://github.com/modern-agile-team/modern-kit/pull/239
useLocalStorage와 유사하지만 localStorage가 아닌 sessionStorage를 활용하는 커스텀 훅입니다.

feat(react): useSessionStorage 신규 훅 추가

---

.changeset/violet-moons-glow.md
docs/docs/react/hooks/useIntersectionObserver.mdx
packages/react/src/hooks/useIntersectionObserver/index.ts
packages/react/src/hooks/useIntersectionObserver/useIntersectionObserver.spec.tsx

useIntersectionObserver enabled 옵션 추가
`enabled`옵션을 통해 `onIntersect*` 콜백 함수들의 호출을 제어 할 수 있습니다. `false`라면 타겟 엘리먼트가 Viewport에 노출하더라도 실행되지 않습니다.

feat(react): useIntersectionObserver enabled 옵션 추가

---

.changeset/shy-clocks-return.md
docs/docs/utils/array/difference.md
packages/utils/src/array/difference/difference.spec.ts
packages/utils/src/array/difference/index.ts
packages/utils/src/array/index.ts
packages/utils/src/array/intersection/index.ts

Issue: #185 
첫번째 배열을 기준으로 두번째 배열과 `중복된 요소를 제외해 고유한 값만을 갖는` 새로운 배열을 반환하는 함수입니다.
기본적으로 `원시 값`에 대해서만 중복 요소를 판단하며, 필요 시 3번째 인자인 `iteratee` 함수 결과로 중복 요소임을 판단 할 수 있습니다.

feat(utils): difference 함수 추가 완료

---

.changeset/eight-seals-know.md
docs/docs/react/hooks/useMouse.mdx
docs/docs/react/hooks/useVhProperty.mdx
packages/react/src/hooks/useVhProperty/index.ts
packages/react/src/hooks/useVhProperty/useVhProperty.spec.ts

기존 useVhProperty의 enabledResize 옵션을 사용하려면 무조건 name 인자를 추가해줘야한다는 불편함이 있었습니다.
따라서 이런 불편함을 해결하기 위해 하나의 options로 변경합니다. -> 네이밍도 `UseVhPropertyProps`로 변경합니다.
추가로 boolean형태의 옵션 네이밍에서 enable보다 enabled 형태가 많이 사용되는 것 같아 enableResize에서 enabledResize 로 네이밍을 변경합니다. 🙏
```ts
// as-is
// name이 기본 값과 동일한 'vh'임에도 넣어줘야했음
useVhProperty('vh', {
enableResize: true,
})
// to-be
useVhProperty({
enabledResize: true,
})
```

fix(react): useVhProperty 옵션 및 문서 수정

---

.changeset/forty-bugs-do.md
docs/docs/react/hooks/useStep.mdx
packages/react/src/hooks/index.ts
packages/react/src/hooks/useStep/index.ts
packages/react/src/hooks/useStep/useStep.spec.ts

Issue: https://github.com/modern-agile-team/modern-kit/issues/252
`mult-step process`의 `step`을 관리하고 추적해주는 커스텀 훅입니다.
내부적으로 쿼리스트링과 router에 의존하는 slash/Funnel과는 차이가 있는 훅입니다.
해당 훅은 router 등과 의존성이 없이 단순히 multi-step 프로세스에서 step을 관리하기 위한 커스텀 훅입니다. 
multi-step process의 대표적인 예로 `carousel slider` 가 있습니다.
해당 훅을 선언적으로 활용하기 위한 `Step` 컴포넌트까지 추후 작업이 가능합니다.
nextStep, preStep 등은 인자로 action을 받아 추가적인 행동을 취할 수 있습니다.
https://github.com/modern-agile-team/modern-kit/assets/64779472/5ebaddb6-ef41-4818-b7c6-bc809f82a3aa
https://github.com/modern-agile-team/modern-kit/assets/64779472/da677687-528a-4ae1-b28c-586b72bedf8b
https://usehooks-ts.com/react-hook/use-step

feat(react): useStep 훅 추가

---

.changeset/two-jars-reflect.md
packages/utils/src/array/intersection/index.ts

Issue: #265 
별도의 함수를 두어 계산하던 중복제거 intersection을 가독성을 위해 intersectionWithDuplicates와 uniq 함수의 조합으로 변경하였습니다.
내부구현만 변경하였기에 테스트코드와 문서에는 수정사항이 없습니다.

chore(utils): intersection 내부구현 수정 완료

---

.changeset/poor-cheetahs-admire.md
docs/docs/utils/array/excludeElements.md
packages/utils/src/array/excludeElements/excludeElements.spec.ts
packages/utils/src/array/excludeElements/index.ts

cc. @Collection50 
excludeElements 성능 개선을 위해 인터페이스 및 내부 로직 변경합니다.
매번 `JSON.stringify`를 하는 것은 불 필요합니다. 필요한 경우 3번째 인자로 `iteratee` 함수를 넣는 방향으로 변경합니다.
이를 통해, 사용자가  제거 할 요소를 결정하는데 `자유롭게`결정 할 수 있으며 성능도 개선 할 수 있습니다. 
- 예를 들어 객체의 경우 단순 프로퍼티 접근을 통해 결정 할 수 있습니다. 
- iteratee의 기본 함수는 `identity` 함수입니다.
또한, 이런 변화를 통해 2번째 인자는 앞으로 배열을 넣어줘야 합니다.
```ts
excludeElements([1, 2, 3, 4, 5, 6], [1, 3]); // [2, 4, 5, 6]
```
```ts
const people = [
{ name: 'kim', address: { city: 'Seoul' } },
{ name: 'lee', address: { city: 'NewYork' } },
{ name: 'kim', address: { city: 'Seoul' } },
];
excludeElements(
people,
[{ name: 'kim', address: { city: 'Seoul' } }],
(item) => item.name
);
// name으로 판단
// [{ name: 'lee', address: { city: 'NewYork' } }]
```
```ts
const array = [
[3, 'a'],
[4, 'b'],
[3, 'a'],
];
const …
```

fix(utils): excludeElements 성능 개선을 위해 인터페이스 변경

---

.changeset/curly-rivers-relate.md
docs/docs/react/components/Iterator.mdx
docs/docs/react/components/SeparatedIterator.mdx
packages/react/src/components/SeparatedIterator/SeparatedIterator.spec.tsx
packages/react/src/components/SeparatedIterator/index.tsx
packages/react/src/components/index.ts

Issue: https://github.com/modern-agile-team/modern-kit/issues/269
[Iterator](https://modern-agile-team.github.io/modern-kit/docs/react/components/Iterator)를 확장해 `items props`로 주어진 배열을 반복하면서 각 항목에 대해 `특정 요소 및 컴포넌트`를 렌더링하며, 동시에 각 요소 사이에 `Separator`를 렌더링 하는 컴포넌트입니다.
기본적으로 마지막 요소 다음 `Separator`는 제외됩니다. `includeLastSeparator`를 `true`로 설정해서 포함시킬 수 있습니다.
```tsx
<SeparatedIterator
items={items}
renderItem={(item) => <h3>{item}</h3>}
separator={<Divider />}
/>
```

feat(react): SeparatedIterator 신규 컴포넌트 추가

---

.changeset/clever-panthers-bake.md
docs/docs/react/components/ClientOnly.mdx
packages/react/src/components/ClientOnly/ClientOnly.spec.tsx
packages/react/src/components/ClientOnly/index.tsx
packages/react/src/components/index.ts

Issue: #260 
컴포넌트가 브라우저에 mount 되었을 때 children이 나타나게 해주는 컴포넌트입니다. mount 전에는 fallback으로 넣어준 컴포넌트를 보여줍니다.

feat(react): ClientOnly 컴포넌트 작업 완료

---

.changeset/afraid-ravens-rescue.md
docs/docs/utils/validator/isReference.md
packages/utils/src/validator/index.ts
packages/utils/src/validator/isReference/index.ts
packages/utils/src/validator/isReference/isReference.spec.ts

Issue: #218 
주어진 인자가 `참조 타입`인지 여부를 확인하는 함수입니다.
```javascript
const reference = isReference({}); // true
const reference = isReference([]); // true
const reference = isReference(new Set()); // true
const reference = isReference(new Map()); // true
const reference = isReference(new WeakSet()); // true
const reference = isReference(new WeakMap()); // true
const reference = isReference(new Date()); // true
const reference = isReference(new Error()); // true
```

feat(utils): isReference 유틸 함수 추가

---

.changeset/curly-papayas-study.md
docs/docs/utils/object/omit.md
packages/utils/src/common/deepCopy/index.ts
packages/utils/src/object/omit/index.ts
packages/utils/src/object/omit/omit.spec.ts

fix(utils): omit 타입 변경 및 deepCopy 개선

---

.changeset/quick-dolphins-serve.md
docs/docs/utils/array/flatten.md
packages/utils/src/array/flatten/flatten.spec.ts
packages/utils/src/array/flatten/index.ts
packages/utils/src/array/index.ts

Issue: https://github.com/modern-agile-team/modern-kit/issues/302
중첩 배열을 `평탄화`해주는 함수입니다. `depth` 옵션으로 평탄화 깊이를 직접 지정 할 수 있습니다.
JS에서 기본적으로 제공하는 [flat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat)은 기본적으로 성능이 안좋습니다.
해당 flatten 함수는 `js의 flat`과 `lodash의 flattenDepth`보다 성능적으로 우수합니다.

feat(utils): flatten 신규 유틸 함수 추가

---

.changeset/warm-falcons-sleep.md
docs/docs/react/components/Iterator.mdx
docs/docs/react/components/SeparatedIterator.mdx
packages/react/src/components/Iterator/Iterator.spec.tsx
packages/react/src/components/Iterator/index.tsx
packages/react/src/components/SeparatedIterator/SeparatedIterator.spec.tsx
packages/react/src/components/SeparatedIterator/index.tsx
packages/types/src/Reference/index.ts
packages/utils/src/validator/isPlainObject/index.ts
packages/utils/src/validator/isReference/index.ts

Iterator는 Fragment에 매번 uniqueKey를 할당하는건 적절하지 않습니다. 따라서, itemKey props를 활용해 이를 지정 할 수 있게 합니다. 만약 매칭되는게 없다면 Index를 key로 갖습니다.
SeparatedIterator는 seperatorInterval 값을 갖습니다. 이를 통해 특정 간격 만큼 separator를 렌더링 할 수 있습니다.

fix(react): 컴포넌트 개선 Iterator, SeparatedIterator

---

docs/docs/utils/array/intersection.md
packages/utils/src/array/intersection/index.ts
packages/utils/src/array/intersection/intersection.bench.ts
packages/utils/src/array/intersectionWithDuplicates/index.ts
packages/utils/vitest.config.ts

fix(utils): intersection 기능 개선 및 밴치마크 추가
intersectionWithDuplicates 는 비교 대상이 없어 밴치마크 테스트 제외
- lodash의 intersectionBy보다  평균적으로 `약 2배` 더 빠릅니다.

fix(utils): intersection 기능 개선 및 밴치마크 추가

---

.changeset/tricky-crabs-clap.md
docs/docs/utils/array/flatten.md
docs/docs/utils/array/flattenDeep.md
packages/utils/src/array/flattenDeep/flattenDeep.bench.ts
packages/utils/src/array/flattenDeep/flattenDeep.spec.ts
packages/utils/src/array/flattenDeep/index.ts

Issue: #307 
기존에 생성된 flatten 을 기반으로 `모든 깊이의 중첩 배열`을 `평탄화`해주는 함수입니다.
JS의 **[Array.prototype.flat(Infinity)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat)** 와 비교했을 때 `성능면에서 우수`하며, 더욱 `정확한 타입 추론`을 할 수 있습니다.
```ts title="typescript"
// as-is 
// Array.prototype.flat(Infinity)
const arr = [1, [2, [3]]].flat(Infinity);
/*
* const arr: FlatArray<number | (number | number[])[], 0 | 1 | 2 | 3 | -1 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20>[]
*/
```
```ts title="typescript"
// to-be 
// flattenDeep
const arr = flattenDeep([1, [2, [3]]]);
/*
* const arr: number[]
*/
```
- lodash의 flattenDeep 보다 약 `1.4배` 빠름
- flat(Infinity)보다 약 `6배` 빠름
[Contributing Guide](https://github.com/modern-agile-team/modern-kit/blob/main/.gith …

feat(utils): flattenDeep 함수 추가

---

.changeset/tidy-eagles-kiss.md
docs/docs/react/hooks/useMediaQuery.mdx
docs/docs/react/hooks/usePreferredColorScheme.mdx
packages/react/src/hooks/index.ts
packages/react/src/hooks/useMediaQuery/index.ts
packages/react/src/hooks/useMediaQuery/useMediaQuery.spec.ts
packages/react/src/hooks/usePreferredColorScheme/index.ts
packages/react/src/hooks/usePreferredColorScheme/usePreferredColorScheme.spec.ts

Issue: #288 
사용자의 색상 스킴 선호도(**[prefers-coloc-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)**) 에 따라 `dark`, `light`, 또는 `no-preference`를 반환합니다.
- ligth: 사용자가 시스템에 `ligth` 테마를 사용하는 것을 선호하거나 선호하는 테마를 알리지 않았을 때 반환합니다.
- dark: 사용자가 시스템에 `dark` 테마를 사용하는 것을 선호한다고 알렸을 때 반환합니다.
사용자는 `운영체제 설정`이나 `사용자 에이전트 설정`에서 선호하는 테마를 지정 할 수 있습니다.
<br />

feat(react): usePreferredColocScheme 신규 훅 추가

---

.changeset/rotten-emus-thank.md
docs/docs/utils/common/size.md
packages/utils/src/common/size/index.ts
packages/utils/src/common/size/size.bench.ts
packages/utils/src/common/size/size.spec.ts

Issue: #334 
주어진 값의 크기를 반환합니다. 크기는 값의 유형에 따라 결정됩니다:
- 문자열의 경우, 문자 수를 반환합니다.
- 배열, NodeList 및 HTMLCollection의 경우, 요소의 수를 반환합니다.
- Set 및 Map의 경우, 항목 수를 반환합니다.
- 일반 객체의 경우, 자체 열거 가능한 속성의 수를 반환합니다.
- 그 외 숫자, WeakMap, WeakSet 등의 타입은 허용하지 않습니다.

feat(utils): size 신규 유틸 함수 추가

---

.changeset/twenty-bats-leave.md
docs/docs/utils/array/shuffle.md
packages/utils/src/array/index.ts
packages/utils/src/array/shuffle/index.ts
packages/utils/src/array/shuffle/shuffle.bench.ts
packages/utils/src/array/shuffle/shuffle.spec.ts

Issue: #335 
배열 요소의 위치를 무작위로 변경해주는 shuffle 함수를 추가합니다.
[Fisher–Yates shuffle의 현대 알고리즘](https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle#The_modern_algorithm)을 기반으로 구현됐습니다.
- lodash보다 약 1.5배 더 빠릅니다.

feat(utils): shuffle 신규 함수 추가

---

.changeset/seven-grapes-greet.md
docs/docs/utils/array/mapRight.md
packages/utils/src/array/index.ts
packages/utils/src/array/mapRight/index.ts
packages/utils/src/array/mapRight/mapRight.spec.ts

Issue: #299 
주어진 배열의 각 요소에 대해 `오른쪽에서 왼쪽으로` 순회하며 제공된 `콜백 함수`를 호출하고, 결과를 새로운 배열로 반환하는 함수입니다!
기존 ES6 `map` 함수 매개변수(callback의 value, index, array, thisArg)을 따라 mapRight 함수를 구현했습니다. 

feat(utils): mapRight 유틸 함수 추가

---

.changeset/soft-beans-return.md
docs/docs/react/hooks/useCycleList.mdx
docs/docs/react/hooks/useStep.mdx
packages/react/src/hooks/index.ts
packages/react/src/hooks/useCycleList/index.ts
packages/react/src/hooks/useCycleList/useCycleList.spec.ts
packages/react/src/hooks/useStep/index.ts
packages/react/src/hooks/useStep/useStep.spec.ts

Issue: #350 
useCycleList 신규  훅 추가 및 간헐적으로 useStep 훅의 테스트 실패하기 때문에 이를 개선하기위해 waitFor를 추가합니다.
또한, 좀 더 범용적으로 사용하기 위해 StepAction의 네이밍을 Action으로 바꾸고 인자의 네이밍도 step을 제거합니다.

feat(react): useCycleList 신규  훅 추가

---

.changeset/happy-cats-wave.md
docs/docs/utils/object/mapValues.md
packages/utils/src/object/index.ts
packages/utils/src/object/mapValues/index.ts
packages/utils/src/object/mapValues/mapValues.bench.ts
packages/utils/src/object/mapValues/mapValues.spec.ts

Issue: #320 
`mapValues` 주어진 객체의 각 값에 대해 제공된 변환 함수를 호출하여 새 객체를 생성하는 함수입니다.
기존에 `mapValues` 함수를 구현할 때 `object` 매개변수 타입에 심볼 타입을 추가하여 작업을 진행했었습니다.
심볼 타입을 사용하면 심볼 `Object.getOwnPropertySymbols` 같은 메서드를 사용해야 하는데, 추가적으로 문자열 키만을 처리할 떄 보다 조건 연산 코드가 생기고, 대부분 mapValues 함수에서 `object` 매개변수에 심볼을 드물게 사용하는 것 같아, 
`object` 타입에서 심볼 타입을 제외하고 string과 number 타입만 포함해서 `mapValues` 함수를 구현했습니다. 
```typescript
object: Record<string | number | symbol, T> -> object: Record<string | number, T> 
```
심볼 타입을 제외하는 게 더 나은 접근일지 이 부분 메인테이너 분의 피드백을 받아보고 싶습니다. 
감사합니다.

feat(utils) mapValues 유틸 함수 추가

---

.changeset/tidy-falcons-hide.md
docs/docs/utils/array/swap.md
packages/utils/src/array/index.ts
packages/utils/src/array/shuffle/index.ts
packages/utils/src/array/swap/index.ts
packages/utils/src/array/swap/swap.spec.ts

Issue: #347 
배열 내 두 요소의 위치를 교환하며, 옵션에 따라 원본 배열을 수정하거나 새로운 배열을 반환합니다.

feat(utils) swap 함수 추가

---

.changeset/shaggy-emus-shave.md
docs/docs/react/hooks/useClipboard.mdx
docs/docs/react/hooks/useCycleList.mdx
docs/docs/utils/array/excludeElements.md
docs/docs/utils/array/fill.md
docs/docs/utils/array/forEachRight.md
docs/docs/utils/array/mapRight.md
docs/docs/utils/clipboard/copyClipboardImage.md
docs/docs/utils/clipboard/readClipboardContents.md
docs/docs/utils/clipboard/readClipboardText.md
packages/react/src/hooks/useClipboard/index.ts
packages/react/src/hooks/useCycleList/index.ts
packages/utils/src/array/excludeElements/index.ts
packages/utils/src/array/fill/index.ts
packages/utils/src/array/forEachRight/index.ts
packages/utils/src/array/mapRight/index.ts
packages/utils/src/clipboard/copyClipboardImage/copyClipboardImage.utils.ts
packages/utils/src/clipboard/copyClipboardImage/index.ts
packages/utils/src/clipboard/copyClipboardText/index.ts
packages/utils/src/clipboard/copyFallbackClipboardText/index.ts
packages/utils/src/clipboard/index.ts
packages/utils/src/clipboard/readClipboardContents/index.ts
packages/utils/src/clipboard/readClipboardText/index.ts
packages/utils/src/object/groupBy/index.ts
packages/utils/src/string/serialize/internal.ts

feat: clipboard read 관련 유틸 함수 추가 및 useClipboard 기능 추가

feat: clipboard read 관련 유틸 함수 추가 및 useClipboard 기능 추가

---

docs/docs/react/hooks/useClipboard.mdx
packages/react/src/hooks/useClipboard/index.ts

docs: useClipboard 문서 수정

---

.changeset/young-rats-lick.md
docs/docs/react/hooks/useLocalStorage.mdx
docs/docs/react/hooks/useSessionStorage.mdx
packages/react/src/hooks/useDocumentTitle/index.ts
packages/react/src/hooks/useForceUpdate/index.ts
packages/react/src/hooks/useLocalStorage/index.ts
packages/react/src/hooks/useOnClickOutside/index.ts
packages/react/src/hooks/useSessionStorage/index.ts
packages/utils/src/device/isMobile/index.ts

refac(react): storage setState 타입 변경 및 ts-doc 추가

refac(react): storage setState 타입 변경 및 ts-doc 추가

---

packages/react/src/hooks/useDebouncedInputValue/index.ts

fix: useDebouncedInputValue 내부 로직 변경

---

.changeset/ten-garlics-smoke.md
docs/docs/react/hooks/useEventListener.mdx
packages/react/src/hooks/useEventListener/index.ts
packages/react/src/hooks/useEventListener/useEventListener.utils.ts
packages/react/src/hooks/useHover/index.ts
packages/react/src/hooks/useMouse/index.ts
packages/react/src/hooks/useOutsidePointerDown/index.ts
packages/react/src/hooks/usePreferredColorScheme/index.ts

fix(react): useEventListener ref 대응 추가

fix(react): useEventListener ref 이슈 대응 작업

---

.changeset/many-pumpkins-tie.md
packages/react/src/hooks/useBlockPromiseMultipleClick/index.ts

해당 훅 사용 시 Error 상황에서 isLoading값이 변경되지 않는 이슈가 있어 코드를 수정했습니다.
그 과정에서 기존에 blockMultipleClick 함수가 훅 내부에서 state의 변경에도 불필요하게 재생성되지 않도록 memoization을 적용했습니다.

fix(react): useBlockPromiseMultipleClick 

---

.changeset/fuzzy-countries-compare.md
docs/docs/react/hooks/useToggleState.mdx
packages/react/src/hooks/index.ts
packages/react/src/hooks/useToggle/index.ts
packages/react/src/hooks/useToggleState/index.ts
packages/react/src/hooks/useToggleState/useToggleState.spec.ts

Issue: #491 
두 개의 값을 토글하는 기능을 제공하는 훅입니다.
기본값으로 제공된 두 개의 값을 관리하며, 선택된 값과 두 값을 토글할 수 있는 함수를 반환합니다.

feat(react): useToggleState 훅 추가

---

.changeset/ten-taxis-camp.md
docs/docs/utils/array/xor.md
packages/react/src/hooks/useHover/index.ts
packages/utils/src/array/index.ts
packages/utils/src/array/xor/index.ts
packages/utils/src/array/xor/xor.spec.ts

헬퍼 함수(`processArray`)와 사용자 지정 매핑 함수(`iteratee`)를 사용하여 두 배열의 대칭 차이(xor) 계산 함수 구현했습니다. 
Issue: #438

feat(utils): xor 유틸 함수 추가

---

.changeset/heavy-onions-allow.md
docs/docs/react/hooks/useFocus.mdx
packages/react/src/hooks/index.ts
packages/react/src/hooks/useFocus/index.ts
packages/react/src/hooks/useFocus/useFocus.spec.tsx

Issue: #352 
`ref`가 할당된 element가 focus 상태인지를 반환하고, 강제로 포커스할 수 있는 함수를 제공합니다.
- `ref`를 등록하지 않거나, 액션(`focusAction`, `blurAction`)을 등록하지 않았을 경우 에러를 던지지 않고, 아무런 동작하지 않습니다.
```tsx
const { ref, isFocus, setFocus } = useFocus<HTMLInputElement>({
focusAction: () => console.log("focus"),
blurAction: () => console.log("blur"),
});
return (
<div>
<input ref={ref} />
<button onClick={() => setFocus()}>focus trigger</button>
<div>{isFocus ? 'Focus' : 'Blur'}</div>
</div>
)
```

feat(react): useFocus 신규 훅 추가

---

.changeset/nasty-suns-trade.md
docs/docs/utils/object/findLastKey.md
packages/utils/src/object/findLastKey/findLastKey.bench.ts
packages/utils/src/object/findLastKey/findLastKey.spec.ts
packages/utils/src/object/findLastKey/index.ts
packages/utils/src/object/index.ts

Issue: #450 
객체에서 조건에 부합하는 마지막 key를 반환합니다.

feat(utils): findLastKey 함수 추가

---

.changeset/friendly-dolls-hide.md
docs/docs/utils/style/formatSizeStyleValue.md
packages/utils/src/style/formatSizeStyleValue/formatSizeStyleValue.spec.ts
packages/utils/src/style/formatSizeStyleValue/index.ts
packages/utils/src/style/index.ts

Issue: #345
number값을 suffix를 붙여 css 스타일 값으로 사용할 수 있게 반환합니다.
suffix는 옵션널하고 디폴트로 px를 사용합니다.

feat(utils): formatSizeStyleValue 함수 추가

---

.changeset/yellow-carpets-bow.md
docs/docs/react/components/ClientGate.mdx
docs/docs/react/components/Mounted.mdx
packages/react/src/components/ClientGate/ClientGate.spec.tsx
packages/react/src/components/ClientGate/index.tsx
packages/react/src/components/Mounted/Mounted.spec.tsx
packages/react/src/components/Mounted/index.tsx
packages/react/src/components/index.ts
packages/types/src/NonEmptyArray/index.ts
packages/types/src/index.ts

Issue: #513 
Client Side에서는 children을, Server Side에서는 fallback component를 보여주는 컴포넌트입니다.
Pure CSR 환경에서 렌더시에는 첫 라이프 사이클이 수행되어 mount가 완료되기 전부터 해당 component를 보여줍니다.

ClientGate 컴포넌트 추가

---

.changeset/brown-ants-pretend.md
docs/docs/utils/validator/isInRange.md
packages/utils/src/math/range/index.ts
packages/utils/src/math/range/range.spec.ts
packages/utils/src/validator/isInRange/index.ts
packages/utils/src/validator/isInRange/isInRange.bench.ts
packages/utils/src/validator/isInRange/isInRange.spec.ts

fix(utils): isInRange, range 로직 개선 및 한글화

fix(utils): isInRange, range 로직 개선 및 한글화

---

.changeset/pink-dolphins-cheer.md
docs/docs/react/components/LazyImage.mdx
docs/docs/react/hooks/useBeforeUnload.mdx
packages/react/src/components/ClientGate/ClientGate.spec.tsx
packages/react/src/components/LazyImage/LazyImage.spec.tsx
packages/react/src/components/LazyImage/index.tsx
packages/react/src/components/Mounted/Mounted.spec.tsx
packages/react/src/hooks/index.ts
packages/react/src/hooks/useBeforeUnload/index.ts
packages/react/src/hooks/useBeforeUnload/useBeforUnload.spec.ts
packages/react/src/hooks/useEventListener/index.ts
packages/react/src/hooks/useEventListener/useEventListener.spec.tsx
packages/react/src/hooks/useToggle/useToggle.spec.tsx

feat(react): useBeforUnload 훅 추가

feat(react): useBeforUnload 훅 추가

---

.changeset/mighty-kings-approve.md
docs/docs/utils/math/clamp.md
packages/utils/src/math/clamp/clamp.bench.ts
packages/utils/src/math/clamp/clamp.spec.ts
packages/utils/src/math/clamp/index.ts
packages/utils/src/math/index.ts

입력된 값이 최소값보다 작으면 최소값을, 최대값보다 크면 최대값을 반환합니다. 값이 범위 내에 있다면 그대로 반환합니다.
<br />
---
<br />
매번 잘 참고하고 있습니다!
changeset을 해주지 않아도 merge 될 때 알아서 버저닝이 되나요? 아니면 changeset 작업이 필요한가요? changeset-bot이 보여서요!

feat(utils): clamp 추가

---

.changeset/hot-windows-divide.md
docs/docs/react/components/DebounceWrapper.mdx
packages/react/src/components/DebounceWrapper/DebounceWrapper.spec.tsx
packages/react/src/components/DebounceWrapper/index.tsx
packages/react/src/components/SwitchCase/SwitchCase.test.tsx
packages/react/src/components/SwitchCase/index.tsx
packages/react/src/hooks/useDebounce/index.ts

fix(react): SwithCase 인터페이스 개선 및 한글화

fix(react): SwithCase 인터페이스 개선 및 한글화

---

.changeset/polite-bulldogs-peel.md
docs/docs/react/hooks/useDependencyTimeout.mdx
packages/react/src/hooks/index.ts
packages/react/src/hooks/useDependencyTimeout/index.ts
packages/react/src/hooks/useDependencyTimeout/useDependencyTimeout.spec.tsx
packages/react/src/hooks/useTimeout/useTimeout.spec.tsx

Issue: #372 
#372 에서 아래와 같은 인터페이스를 명시해주셔서 이렇게 구현했습니다.
```js
/*
callback: 실행 할 콜백
delay: timeout delay
deps: 의존성 배열
callOnMount: 최초 마운트 시에 callback 호출 할 것인지 결정
*/
useDependencyTimeout(callback, delay, deps, { callOnMount });
```
그런데 `useTimout`을 사용한 구현인만큼, `useTimeout`의 `options`도 사용할 수 있어야 하지 않을까 하는 고민이 존재했는데요.
```js
/*
callback: 실행 할 콜백
options: TimeoutOptions & { deps unknown }
callOnMount: 최초 마운트 시에 callback 호출 할 것인지 결정
*/
useDependencyTimeout(callback, delay, deps, { callOnMount });
```
객체로 받는 것이 아니라 인수로 받는 경우 생각보다 인수가 많아질 수도 있다고 생각해 고민이 되었습니다.
```js
/*
callback: 실행 할 콜백
options: TimeoutOptions
delay: timeout delay
deps: 의존성 배열
callOnMount: 최초 마운트 시에 callback 호출 할 것인지 결정
*/
useDependencyTimeout(callback, delay, deps, { callOnMount });
```
의견 주시면 감사하겠습니다. 
PS.
개인적으로 바빠서 작업이 늦어졌습니다 !! …

feat(react): useDependencyTimeout 구현

---

.changeset/orange-gifts-poke.md
docs/docs/react/hooks/useAsyncEffect.mdx
packages/react/src/hooks/index.ts
packages/react/src/hooks/useAsyncEffect/index.ts
packages/react/src/hooks/useAsyncEffect/useAsyncEffect.spec.ts
packages/react/src/hooks/useDependencyTimeout/index.ts

Issue: 
일반적으로 `useEffect`에 전달하는 콜백 함수는 비동기 함수를 사용할 수 없습니다.
`useAsyncEffect`는 `비동기 함수`를 `useEffect`와 함께 사용하기 위한 커스텀 훅입니다.

feat(react): useAsyncEffect 신규 훅 추가

---

.changeset/young-garlics-smile.md
packages/types/src/ArrayWithReadonly/index.ts
packages/types/src/DistributiveOmit/DistributiveOmit.spec.ts
packages/types/src/DistributiveOmit/index.ts
packages/types/src/ExtractMapType/index.ts
packages/types/src/ExtractSetType/ExtractSetType.spec.ts
packages/types/src/ExtractSetType/index.ts
packages/types/src/NegativeNumber/index.ts
packages/types/src/ReadonlyArray/index.ts
packages/types/src/WholeNumber/index.ts
packages/types/src/index.ts

feat(types): DistributiveOmit 타입 추가
```ts
type Union = { a: string } | { b: number }
type Result = DistributiveOmit<Union, 'a'>
// 동작 원리와 순서
// 1. Result = DistributiveOmit<Union, 'a'>
// 2. Result = Omit<{ a: string }, 'a'> | Omit<{ b: number }, 'a'>
// 3. Result = {} | { b: number }
```

feat(types): DistributiveOmit 타입 추가

---

.changeset/nine-brooms-obey.md
docs/docs/utils/date/isAfterDate.md
docs/docs/utils/date/isBeforeDate.md
packages/utils/src/date/getDDay/index.ts
packages/utils/src/date/isAfterDate/index.ts
packages/utils/src/date/isAfterDate/isAfterDate.spec.ts
packages/utils/src/date/isBeforeDate/index.ts
packages/utils/src/date/isBeforeDate/isBeforeDate.spec.ts

feat(utils): isAfterDate, isBeforeDate 추가
- `비교 날짜(compareDate)`가 없을 때 현재 날짜를 기준으로 목표 날짜가 현재 날짜보다 이후인 경우 `true`를 반환합니다.
```ts title="typescript"
import { isAfterDate } from '@modern-kit/utils';
// 현재 날짜가 2025년 1월 1일 00:00:00 일 때
isAfterDate({ targetDate: new Date('2025-01-02') }); // true
isAfterDate({ targetDate: new Date('2024-12-31') }); // false
// 문자열 포맷도 허용합니다.
isAfterDate({ targetDate: '2025-01-02' }); // true
```
- `비교 날짜(compareDate)`가 있을 때 목표 날짜가 비교 날짜보다 이후인 경우 `true`를 반환합니다.
```ts title="typescript"
import { isAfterDate } from '@modern-kit/utils';
isAfterDate({ targetDate: new Date('2025-01-01'), compareDate: new Date('2024-12-31') }); // true
isAfterDate({ targetDate: new Date('2024-12-31'), compareDate: new Date('2025-01-01') }); // false
// 문자열 포맷도 허용합니다.
isAfterDate({ …
```

feat(utils): isAfterDate, isBeforeDate 추가

---

.changeset/swift-bananas-work.md
docs/docs/utils/date/isDateInRange.md
packages/utils/src/date/isDateInRange/index.ts
packages/utils/src/date/isDateInRange/isDateInRange.spec.ts

issue: #653 
- 타겟 날짜가 있다면 `타겟 날짜`가 범위 내에 있는지 확인하며, 타겟 날짜가 없다면 `현재 날짜`가 범위 내에 있는지 확인합니다.
```ts title="typescript"
import { isDateInRange } from '@modern-kit/utils';
// 현재 날짜가 2025년 01월 01일 기준
isDateInRange({ fromDate: new Date('2024-01-01'), toDate: new Date('2024-12-31') }); // false
isDateInRange({ fromDate: '2025-01-01', toDate: '2025-12-31' }); // true
isDateInRange({ targetDate: '2025-01-02', fromDate: '2025-01-01', toDate: '2025-01-03' }); // true
```
- 시작 날짜만 지정하여 `타겟 날짜(or 현재 날짜)`가 시작 날짜 이후인지 확인합니다.
```ts title="typescript"
import { isDateInRange } from '@modern-kit/utils';
// 현재 날짜가 2025년 01월 01일 기준
isDateInRange({ fromDate: new Date('2025-01-02') }); // true
isDateInRange({ fromDate: '2024-12-31' }); // false
isDateInRange({ targetDate: '2025-01-02', fromDate: '2025-01-01' }); // …
```

feat(utils): isDateInRange 함수 추가

---

.changeset/tough-drinks-bathe.md
.changeset/weak-colts-love.md
docs/docs/utils/date/getAge.md
docs/docs/utils/date/isUnderAge.md
packages/utils/src/date/getAge/getAge.spec.ts
packages/utils/src/date/getAge/index.ts
packages/utils/src/date/index.ts
packages/utils/src/date/isUnderAge/index.ts
packages/utils/src/date/isUnderAge/isUnderAge.spec.ts

Issue: #661 
주어진 생년월일을 기준으로 현재 나이를 계산합니다.
```ts
getAge(new Date('2006-01-01')); // 19
getAge('2006-01-01'); // 19
```
<br />
주어진 생년월일을 기준으로 특정 나이보다 어린지 확인합니다.
`inclusive` 값을 기준으로 기준 나이를 포함할지 여부를 결정합니다.
```ts title="typescript"
import { isUnderAge } from '@modern-kit/utils';
// 현재 날짜 2025년 1월 1일 기준
isUnderAge({ birthDate: new Date('2006-01-02'), targetAge: 19 }); // true
isUnderAge({ birthDate: new Date('2006-01-01'), targetAge: 19 }); // false, 정확히 만 19세
isUnderAge({ birthDate: new Date('2005-12-31'), targetAge: 19 }); // false
isUnderAge({ birthDate: '2006-01-02', targetAge: 19 }); // true
isUnderAge({ birthDate: '2006-01-01', targetAge: 19 }); // false, 정확히 만 19세
isUnderAge({ birthDate: '2005-12-31', targetAge: 19 }); // false
```
- `inclusive` 값을 기준으로 기준 나이를 포함할지 여부를 결정합니다. (기본값: …

feat(utils): getAge, isUnderAge 신규 함수 추가

---

docs/docs/utils/formatter/formatNumberWithCommas.md
packages/utils/src/formatter/formatNumberWithCommas/formatNumberWithCommas.spec.ts
packages/utils/src/formatter/formatNumberWithCommas/index.ts

fix: formatNumberWithCommas 로직 수정으로 인터페이스 개선

fix: formatNumberWithCommas 로직 수정으로 인터페이스 개선

---

.changeset/few-badgers-dance.md
packages/types/src/DeepPartial/DeepEqual.spec.ts
packages/types/src/DeepPartial/index.ts
packages/types/src/index.ts

feat: DeepEqual 유틸 타입 추가
객체의 모든 속성을 선택적(optional)으로 만드는 타입
중첩된 객체의 경우에도 재귀적으로 모든 속성을 선택적으로 변환합니다.
```ts
interface User {
name: string;
age: number;
address: {
street: string;
city: string;
};
};
type PartialUser = DeepPartial<User>;
// {
//   name?: string;
//   age?: number;
//   address?: {
//     street?: string;
//     city?: string;
//   };
// }
```

feat: DeepEqual 유틸 타입 추가

---

.changeset/few-badgers-dance.md
packages/types/src/DeepPartial/DeepPartial.spec.ts
packages/types/src/DeepPartial/index.ts

fix: DeepPartial changeset, text 수정

---

.changeset/large-carrots-share.md
docs/docs/react/components/SwithCase.mdx
docs/docs/utils/formatter/formatNumberWithUnits.md
packages/react/src/components/SwitchCase/index.tsx
packages/utils/src/formatter/formatNumberWithUnits/formatNumberWithUnits.spec.ts
packages/utils/src/formatter/formatNumberWithUnits/formatNumberWithUnits.utils.ts
packages/utils/src/formatter/formatNumberWithUnits/index.ts

- SwitchCase 하위 타입스크립트/리액트 버전 타입 호환성을 위해 반환 타입 수정
- 관심사 분리를 위해 formatNumberWithUnits에서 콤마 기능 제거 및 소수점 처리 개선

SwitchCase 하위 타입스크립트/리액트 버전 타입 호환성을 위해 반환 타입 수정

---

.pnp.cjs
packages/react/package.json
packages/types/package.json
packages/utils/package.json
yarn.lock

chore: tslib dependency 수정

---

.changeset/ninety-dolphins-decide.md
docs/docs/utils/validator/isBlob.md
packages/utils/src/validator/index.ts
packages/utils/src/validator/isBlob/index.ts
packages/utils/src/validator/isBlob/isBlob.spec.ts
packages/utils/subPaths.mjs

```ts title="typescript"
import { isBlob } from '@modern-kit/utils';
isBlob(new Blob()); // true
isBlob(new Blob(['content'], { type: 'text/plain' })); // true
isBlob('blob'); // false
isBlob(123); // false
isBlob({ a: 1 }); // false
isBlob([1, 2, 3]); // false
isBlob(null); // false
isBlob(undefined); // false
```

feat(utils): isBlob 함수 추가

---

.changeset/shiny-walls-rush.md
docs/docs/react/hooks/useDidUpdate.mdx
packages/react/src/hooks/index.ts
packages/react/src/hooks/useDidUpdate/index.ts
packages/react/src/hooks/useDidUpdate/useDidUpdate.spec.tsx

Issue: #752 
최초 마운트시에는 실행되지않고 deps값이 업데이트 되었을때 effect를 실행시키는 커스텀 훅입니다.

feat(react): useDidUpdate 신규 훅 추가

---

.changeset/silly-poems-grow.md
docs/docs/react/components/EventExtender.mdx
packages/react/src/components/EventExtender/EventExtender.spec.tsx
packages/react/src/components/EventExtender/index.tsx
packages/react/src/components/FallbackLazyImage/index.tsx
packages/react/src/components/SwitchCase/SwitchCase.test.tsx
packages/react/src/components/index.ts
packages/react/src/hooks/useMediaQuery/useMediaQuery.spec.ts
packages/react/vitest.config.ts

자식 컴포넌트의 이벤트 핸들러를 확장하여 `전후 처리`를 가능하게 하는 컴포넌트입니다.
기본적으로 `isAsync` 옵션은 `false`이며, `동기 이벤트`를 처리합니다.
`isAsync` 옵션을 `true`로 주고, `비동기 이벤트` 를 처리 할 수 있습니다. 이를 통해 `비동기 이벤트 순서 보장`을 할 수 있습니다.
단, `비동기 이벤트`를 처리 할 경우 일반적인 이벤트 호출 순서가 아닌 순서로 이벤트가 호출될 수 있습니다.
이런 현상은 대표적으로 `MouseEvent`를 캡처하는 경우에 발생합니다.
- 예를 들어, `onMouseUp` 이벤트는 `onClick` 이벤트 이전에 호출되는게 일반적이지만, 해당 컴포넌트로 `onMouseUp` 이벤트를 캡처하면 `onMouseUp` 이벤트가 `onClick` 이벤트 이후에 호출됩니다.
- 이러한 현상은 `isAsync`가 `true`일 시 이벤트를 `await` 하기 때문입니다.
```tsx
// 기본 사용법
<EventExtender
capture="onClick"
beforeEvent={(e: React.MouseEvent<HTMLButtonElement>) => {
console.log('클릭 전', e);
}}
afterEvent={(e: React.MouseEvent<HTMLButtonElement>) => {
console.log('클릭 후', e);
}}
>
<button onClick={(e) => console.log('클릭', e)}>
Sync  Button
</button>
</EventExtender>
```
```tsx
// 비동기 …
```

feat(react): EventExtender 신규 컴포넌트 추가

---

.changeset/popular-suits-serve.md
docs/docs/utils/array/zip.md
packages/utils/src/array/index.ts
packages/utils/src/array/zip/index.ts
packages/utils/src/array/zip/zip.spec.ts

Issue: #520 
여러 배열을 결합하여 튜플 형태의 배열을 반환하는 함수입니다.
```ts
export function zip<T>(arr1: T[] | readonly T[]): [T][];
export function zip<T, U>(
arr1: T[] | readonly T[],
arr2: U[] | readonly U[]
): [T, U][];
export function zip<T, U, V>(
arr1: T[] | readonly T[],
arr2: U[] | readonly U[],
arr3: V[] | readonly V[]
): [T, U, V][];
export function zip<T, U, V, W>(
arr1: T[] | readonly T[],
arr2: U[] | readonly U[],
arr3: V[] | readonly V[],
arr4: W[] | readonly W[]
): [T, U, V, W][];
```
```ts
import { zip } from '@modern-kit/utils';
const arr1 = [1, 2, 3];
const arr2 = ['a', 'b', 'c'];
const arr3 = [true, false, true];
const arr4 = [null, null];
zip(arr1);
// [[1], [2], [3]]
zip(arr1, arr2);
// [[1, 'a'], [2, 'b'], [3, 'b']]
zip(arr1, arr2, arr3);
// [[1, 'a', true], [2, 'b', false], [3, 'b', …
```

feat(utils): zip 함수 추가

---

.changeset/thick-keys-collect.md
docs/docs/utils/common/retry.md
packages/utils/src/common/index.ts
packages/utils/src/common/retry/index.ts
packages/utils/src/common/retry/retry.spec.ts

Issue: #773 
Promise를 반환하는 함수가 성공할 때까지 다시 시도하는 함수입니다.
retry함수 구현중 논의하고싶은 내용이 있어서 말씀드립니다!
1. retry 함수와 count 역할을하는 retry 인자값의 네이밍이 중복되는데 가독성 측면에서 혼란을 주지 않는지
2. retry 인자값이 전달되지 않았을 경우의 default값 (현재는 3입니다.)
이외에도 보완사항이 있을 경우 편하게 말씀 주시면 감사드리겠습니다. 🙏

feat(utils): retry 함수 추가

---

.changeset/old-pants-remain.md
docs/docs/react/hooks/useDropZone.mdx
packages/react/src/hooks/index.ts
packages/react/src/hooks/useDropZone/index.ts
packages/react/src/hooks/useDropZone/useDropZone.spec.tsx
packages/react/src/hooks/useVisibilityChange/index.ts

`드래그 앤 드롭 이벤트`를 처리하여 `파일`을 수신할 수 있는 영역을 생성하는 커스텀 훅입니다.
```tsx
const Example = () => {
const { ref, isDragOver } = useDropZone((files) => {
console.log('files', files);
setFileNameList(files.map((file) => file.name));
});
return <div ref={ref}>DropZone</div>;
};
```

feat(react): useDropZone 신규 훅 추가

---

.changeset/old-breads-relate.md
docs/docs/react/hooks/useComputedStyleObserver.mdx
packages/react/src/hooks/index.ts
packages/react/src/hooks/useComputedStyleObserver/index.ts
packages/react/src/hooks/useComputedStyleObserver/useComputedStyleObserver.spec.tsx

관찰할 타겟 요소의 특정 `computed style` 값을 `실시간으로 관찰하고 관리`하는 React 훅
- **[MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver/observe)** 를 사용하여 요소의 스타일 속성이 변경될 때 콜백을 호출합니다.
- **[CSSStyleDeclaration: setProperty](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/setProperty)** 를 사용하여 요소의 스타일 속성을 직접 변경하더라도 이를 실시간으로 반영합니다.
```tsx
const Example = () => {
const { ref, value, setValue } = useComputedStyleObserver('width');
return (
<>
<div ref={ref} style={{ width: '100px', height: '100px', backgroundColor: 'skyblue' }} />
<div>
<p>현재 너비: {`${value}`}</p>
<button onClick={() => setValue('100px')}>너비 100px로 변경(setValue)</button>
<button onClick={() => setValue('300px')}>너비 300px로 변경(setValue)</button>
<br />
<button onClick={() => …
```

feat(react): useComputedStyleObserver 신규 훅 추가

---

.changeset/many-actors-taste.md
packages/react/src/utils/mergeEventHandlers/index.ts
packages/react/src/utils/mergeEventHandlers/mergeEventHandlers.spec.ts
packages/react/src/utils/mergeRefs/index.test.ts
packages/react/src/utils/mergeRefs/index.ts

여러 이벤트를 병합해주는 mergeEventHandlers 함수 추가
```tsx
const handleClick1 = (e:  React.MouseEvent<HTMLButtonElement>) => { /* ... */ }
const handleClick2 = (e:  React.MouseEvent<HTMLButtonElement>) => { /* ... */ }
const handleClick3 = (e:  React.MouseEvent<HTMLButtonElement>) => { /* ... */ }
const mergedClickEvent = mergeEventHandlers(handleClick1, handleClick2, handleClick3);
```
```tsx
<button onClick={mergedClickEvent} />
```

feat(react): mergeEventHandlers 함수 추가

---

packages/react/src/components/LazyImage/index.tsx
packages/react/src/components/OutsidePointerDownHandler/index.tsx
packages/react/src/components/Slot/index.tsx
packages/react/src/utils/index.ts

기존 mergeRefs 사용을 useMergeRefs 사용으로 변경
- mergeRefs 참조형 문제 발생

fix: react/components useMergeRefs 사용으로 변경

---

.changeset/nine-bags-kiss.md
docs/docs/react/hooks/useManualTimeout.mdx
packages/react/src/hooks/index.ts
packages/react/src/hooks/useManualTimeout/index.ts
packages/react/src/hooks/useManualTimeout/useManualTimeout.spec.tsx

수동으로 타임아웃을 설정하고, 초기화할 수 있는 훅입니다.
`useTimeout` 훅과 다르게 초기 자동 실행이 없으며, 명시적으로 타임아웃을 설정해야 합니다.
모든 타임아웃은 해당 훅 언마운트 시 자동으로 초기화됩니다.
`useTimeout`은 hooks rule에 따라 중첩 타임아웃 등 복잡한 타임아웃 설정에 적절하지 않습니다.
`useManualTimeout`은 병렬/중첩된 타임아웃을 실행하고, 한번에 초기화 해야 될 때 유용합니다.
```ts
const [number, setNumber] = useState(0);
const { set } = useManualTimeout();
const handleSetTimeout = () => {
set(() => {
setNumber(number + 1);
}, 1500);
}
useEffect(() => {
set(() => {
setNumber((prev) => prev + 1);
set(() => {
setNumber((prev) => prev + 2);
set(() => {
setNumber((prev) => prev + 3);
}, 1500);
}, 1500);
}, 1500);
}, [set]);
```

feat(react): useManualTimeout 신규 훅 추가

---

.changeset/afraid-melons-wonder.md
packages/types/src/EnumerateNumbers/EnumerateNumbers.spec.ts
packages/types/src/EnumerateNumbers/index.ts
packages/types/src/index.ts

Issue: #893 
0 ~ N-1 번째 까지 숫자 유니언 타입을 생성합니다.
```
type EnumerateNumbers<N, Acc extends number[] = []> = N extends number
? Acc['length'] extends N
? Acc[number]
: EnumerateNumbers<N, [...Acc, Acc['length']]>
: never;
```
number가 아닌 다른 타입을 사용했을 시 never가 반환되도록 수정했습니다.

feat(types): EnumerateNumbers 타입 추가
