.github/workflows/document.yml

fix: workflow

---

.github/workflows/document.yml
README.md

chore: workflow test

---

packages/react/src/components/DebounceWrapper/index.tsx

fix(react): DebounceWrapper

---

.github/workflows/document.yml
packages/react/src/hooks/useAsyncProcessQueue/index.ts

fix: useAsyncProcessQueue

---

.changeset/itchy-boats-melt.md
packages/types/package.json

@modern-kit/types package.json 수정

chore: @modern-kit/types package.json 수정

---

.changeset/gold-cheetahs-clap.md
docs/docs/react/components/InView.mdx
docs/docs/react/components/LazyImage.mdx
docs/docs/react/hooks/useIntersectionObserver.mdx
packages/react/src/components/LazyImage/index.tsx
packages/react/src/hooks/useIntersectionObserver/index.ts

fix: useIntersectionObserver 기능 개선

---

.changeset/curvy-ghosts-fry.md
.pnp.cjs
packages/react/package.json
packages/react/src/components/Portal/Portal.spec.tsx
packages/react/src/components/Portal/index.tsx
packages/react/src/hooks/useAsyncProcessQueue/index.ts
packages/react/src/hooks/useIntersectionObserver/index.ts
packages/react/src/hooks/useMergeRefs/useMergeRefs.spec.tsx
packages/react/src/hooks/useWindowSize/index.ts
packages/react/src/utils/test/mockIntersectionObserver.ts
packages/types/src/Nullable/index.ts
packages/utils/src/storage/getStorageItem/index.ts
packages/utils/src/storage/types.ts
yarn.lock

Applied @modern-kit/types Nullable

refac: applied @modern-kit/types Nullable

---

packages/react/vitest.config.ts
packages/utils/vitest.config.ts

chore: vitest.config

---

.changeset/great-parents-approve.md
docs/docs/react/hooks/useBlockPromiseMultipleClick.mdx
packages/react/src/hooks/index.ts
packages/react/src/hooks/useBlockPromiseMultipleClick/index.ts
packages/react/src/hooks/useBlockPromiseMultipleClick/useBlockPromiseMultipleClick.spec.tsx

https://github.com/modern-agile-team/modern-kit/pull/82
@Sangminnn useBlockPromiseMultipleClick 문서를 추가하였습니다 :) 
그 외 네이밍 변경을 놓친 부분을 수정하였고, 테스트 설명을 개선하였습니다

docs(react): useBlockPromiseMultipleClick 문서 추가

---

.changeset/seven-pants-eat.md
docs/docs/react/components/SwithCase.mdx
docs/docs/react/components/When.mdx
packages/react/src/components/SwitchCase/index.tsx

#100 @soonki-98 SwitchCase 문서 추가

docs: SwitchCase 문서 추가

---

.changeset/sweet-kids-accept.md
packages/utils/src/common/index.ts

#115
cc. @Sangminnn 
packages/utils/src/common/index.ts 파일에 parseJson이 추가되지 않아 추가하였습니다

chore: changeset

---

.changeset/rude-ligers-punch.md
packages/react/src/hooks/useAsyncProcessQueue/index.ts
packages/react/src/hooks/useAsyncProcessQueue/useAsyncProcessQueue.spec.ts
packages/utils/src/common/deepEqual/deepEqual.spec.ts
packages/utils/src/object/mergeProperties/mergeProperties.spec.ts
packages/utils/src/object/omit/index.ts
packages/utils/src/object/pick/index.ts

mergeProperties 테스트 커버리지 개선, useAsyncProcessQueue 테스트 코드 추가

fix: mergeProperties 테스트 커버리지 개선, useAsyncProcessQueue 테스트 코드 추가

---

docs/docs/utils/file/getMIMETypeFromFile.md
docs/docs/utils/validator/isMIMEType.md
packages/utils/src/validator/isMIMEType/index.ts
packages/utils/src/validator/isMIMEType/isMIMEType.spec.ts

fix(utils): isMIMEType 개선

---

packages/utils/src/file/getMIMETypeFromFile/getMIMETypeFromFile.spec.ts
packages/utils/src/file/getMIMETypeFromFile/index.ts
packages/utils/src/file/getMIMETypeFromResponse/getMIMETypeFromResponse.spec.ts
packages/utils/src/file/getMIMETypeFromResponse/index.ts

test(utils): getMIMETypeFromResponse 테스트 코드 추가

---

docs/docs/utils/clipboard/clipboardFallbackTextCopy.md
docs/docs/utils/clipboard/clipboardImageCopy.md
docs/docs/utils/clipboard/clipboardTextCopy.md
packages/utils/src/clipboard/clipboardFallbackTextCopy/index.ts
packages/utils/src/clipboard/clipboardImageCopy/index.ts
packages/utils/src/clipboard/clipboardTextCopy/index.ts

fix(utils): clipboard 관련 함수들 반환 값 추가

---

.changeset/beige-pears-boil.md
codecov.yml
docs/docs/react/hooks/useWindowSize.mdx
packages/react/src/hooks/useImageStatus/useImageStatus.spec.tsx
packages/react/src/hooks/useWindowScrollTo/index.ts
packages/react/src/hooks/useWindowScrollTo/useWindowScrollTo.spec.ts
packages/react/src/hooks/useWindowSize/index.ts

test(react): useWindowScrollTo 테스트 코드 추가

---

.changeset/rich-planets-deliver.md
docs/docs/utils/file/convertImageToBlob.md
packages/utils/src/file/constants.ts
packages/utils/src/file/convertImageToBlob/index.ts
packages/utils/src/file/index.ts

https://github.com/modern-agile-team/modern-kit/issues/130
올려드리기로 했던 convertImageToBlob을 이제서야 리뷰요청드립니다 😂 
코드 전반적으로는 이전 리뷰때 이야기했던 부분과 크게 다르지 않고 인자로 변환할 이미지 타입을 받는 것으로 수정해두었습니다!
docs는 convertImageToBase64과 맥락이 유사하여 비슷하게 작성해두었습니다 🙇 
(테스트코드는 작성이 어려워 일단 제외하고 올립니다!)

feat(utils): convertImageToBlob 함수 추가 완료

---

docs/docs/react/hooks/useClipboard.mdx
docs/docs/utils/clipboard/clipboardFallbackTextCopy.md
docs/docs/utils/clipboard/clipboardImageCopy.md
docs/docs/utils/clipboard/clipboardTextCopy.md
docs/docs/utils/file/convertImageToBase64.md
docs/docs/utils/file/convertImageToBlob.md
packages/react/src/hooks/useClipboard/index.ts
packages/utils/src/clipboard/clipboardImageCopy/index.ts
packages/utils/src/file/constants.ts
packages/utils/src/file/convertImageToBase64/index.ts
packages/utils/src/file/convertImageToBlob/index.ts

clipboardImageCopy 함수 수정 및 문서 개선

fix(utils): clipboardImageCopy 함수 convertImageToBlob 유틸 함수 적용 및 타입/문서 개선

---

.changeset/forty-bottles-drum.md
docs/docs/utils/clipboard/copyClipboardImage.md
docs/docs/utils/clipboard/copyClipboardText.md
docs/docs/utils/clipboard/copyFallbackClipboardText.md
packages/react/src/hooks/useClipboard/index.ts
packages/utils/src/clipboard/copyClipboardImage/index.ts
packages/utils/src/clipboard/copyClipboardText/index.ts
packages/utils/src/clipboard/copyFallbackClipboardText/index.ts
packages/utils/src/clipboard/index.ts

clipboard 관련 함수 네이밍 변경
copy라는 동사가 접두사로 오게끔 수정

fix(utils): clipboard 관련 함수 네이밍 변경

---

packages/utils/src/validator/isFunction/isFunction.spec.ts

- isFunction 테스트를 보완했습니다.
- 지금보니 `utils`가 맞군요..

test(utils): isFunction 테스트 추가

---

.changeset/pink-tips-drive.md
docs/docs/react/hooks/useHover.mdx
packages/react/src/hooks/index.ts
packages/react/src/hooks/useHover/index.ts
packages/react/src/hooks/useHover/useHover.spec.tsx

이전에 이야기나눈 useHover hook을 구현해보았습니다.
참고자료로 주신 use-hooks의 코드도 참고하였고, alibaba의 hooks 레포에 존재하는 useHover hook도 참고하였습니다.
다만 테스트코드를 작성하였으나 계속해서 실패가 나타나 잘못 구현한 부분이 있을지 의견을 여쭤보고자 먼저 풀리퀘 올려드립니다 🙇 
https://github.com/alibaba/hooks/blob/master/packages/hooks/src/useHover/index.ts
- [O] All tests pass.
- [O] All type checks pass.
- [O] I have read the Contributing Guide document.

feat(react): useHover 훅 추가 완료

---

docs/docs/utils/string/countSubstringOccurrences.md
packages/utils/src/common/parseJson/index.ts
packages/utils/src/string/countSubstringOccurrences/countSubstringOccurrences.spec.ts
packages/utils/src/string/countSubstringOccurrences/index.ts

- `countSubstringOccurrences` util 공백에 대한 처리와 특수문자에 대한 처리를 보완했습니다.

fix(utils): 특수 문자에 대한 개수와 공백에 대한 처리 추가

---

docs/docs/utils/common/delay.md
packages/utils/src/common/delay/delay.spec.ts
packages/utils/src/common/delay/index.ts

Issue: https://github.com/modern-agile-team/modern-kit/pull/205#discussion_r1626197439
delay callback 추가 한 작업을 revert합니다.

revert(utils): delay callback 제거

---

packages/utils/src/device/isServer/isServer.spec.ts

- `isServer` 유틸 함수의 테스트 코드 오타를 수정했습니다.

test(isServer): isServer의 test 문구 수정

---

.changeset/angry-boxes-agree.md
docs/docs/utils/number/isFloat.mdx
packages/utils/src/index.ts
packages/utils/src/number/index.ts
packages/utils/src/number/isFloat/index.ts
packages/utils/src/number/isFloat/isFloat.spec.ts

Issue: #228 
Number의 inInteger는 숫자 중 정수만을 판별해냅니다.
isFloat를 사용하면 숫자 중 실수를 판별해낼 수 있습니다.

feat(utils): isFloat 함수 추가 완료

---

.changeset/grumpy-fans-buy.md
docs/docs/react/hooks/useMergeRefs.mdx
packages/react/src/components/InView/index.tsx
packages/react/src/hooks/useMergeRefs/index.ts

가독성을 위해 useMergeRefs 리팩토링 및 타입 개선

fix(react): useMergeRefs 개선

---

.changeset/long-hairs-attack.md
docs/docs/react/components/InView.mdx
docs/docs/react/hooks/useResizeObserver.mdx
docs/docs/react/hooks/useStep.mdx
docs/docs/react/hooks/useStepState.mdx
packages/react/src/hooks/index.ts
packages/react/src/hooks/useStep/index.ts
packages/react/src/hooks/useStepState/index.ts
packages/react/src/hooks/useStepState/useStepState.spec.ts

Issue: https://github.com/modern-agile-team/modern-kit/issues/256
useStep을 확장해 내부적으로 상태를 관리 할 수 있는 훅입니다.

feat(react): useStepState 신규 커스텀 훅 추가

---

docs/docs/react/hooks/useStepState.mdx
packages/react/src/hooks/usePreservedState/index.ts
packages/react/src/hooks/useStepState/index.ts
packages/react/src/hooks/useStepState/useStepState.spec.ts
packages/utils/src/storage/clearStorage/index.ts
packages/utils/src/storage/getStorageItem/index.ts
packages/utils/src/storage/removeStorageItem/index.ts
packages/utils/src/storage/setStorageItem/index.ts

useStepState에 storage 옵션을 추가합니다.

feat(react): useStepState storage 옵션 추가

---

.changeset/strange-mayflies-provide.md
packages/utils/src/math/max/index.ts
packages/utils/src/math/min/index.ts

Issue: #279 
- `math` `util` 함수의 반복문을 `for...of` 문으로 수정했습니다.
- close #279 

fix(util): math util 함수의 반복문을 for...of 문으로 수정

---

docs/docs/utils/array/difference.md
packages/utils/src/array/difference/difference.bench.ts
packages/utils/src/array/difference/index.ts

difference 성능 개선 및 밴치마크 테스트 추가

fix: difference 성능 개선 및 밴치마크 테스트 추가

---

packages/react/src/hooks/useStepState/useStepState.spec.ts

test: useStepState 테스트 실패 수정

---

.changeset/wild-adults-hunt.md
docs/docs/utils/array/forEachRight.md
packages/utils/src/array/forEachRight/forEachRight.spec.ts
packages/utils/src/array/forEachRight/index.ts
packages/utils/src/array/index.ts

Issue: #298 
배열의 요소를 오른쪽에서 왼쪽으로 순회하면서 각 요소에 대해 주어진 콜백 함수를 실행하는 함수입니다.

feat(utils): forEachRight 유틸 함수 추가

---

.changeset/fifty-beers-scream.md
docs/docs/react/hooks/useStep.mdx
packages/react/src/hooks/useStep/index.ts
packages/react/src/hooks/useStep/useStep.spec.ts
packages/react/src/hooks/useStepState/useStepState.spec.ts

배열 인덱스와도 호환될 수 있게 step의 최소 값(1->0) initialStep의 기본 값을 0으로 수정

fix(react): useStep step의 최소 값과  initialStep 기본 값을 0으로 수정

---

.changeset/flat-pigs-hug.md
packages/react/src/hooks/usePreservedCallback/index.ts
packages/react/src/hooks/usePreservedCallback/usePreservedCallback.spec.ts

fix(react): usePreservedCallback 최신 함수 보장 이슈 해결 및 테스트 코드 개선

fix(react): usePreservedCallback 최신 함수 보장 이슈 해결 및 테스트 코드 개선

---

.changeset/twenty-dolls-matter.md

fix: changeset

---

.changeset/green-wombats-whisper.md
.changeset/strong-mugs-flash.md
docs/docs/react/hooks/useScrollTo.mdx
docs/docs/utils/validator/isWindow.md
packages/react/src/hooks/useScrollTo/index.ts
packages/react/src/hooks/useScrollTo/internal.ts
packages/react/src/hooks/useScrollTo/useScrollTo.spec.tsx
packages/utils/src/validator/index.ts
packages/utils/src/validator/isWindow/index.ts
packages/utils/src/validator/isWindow/isWindow.spec.ts

useScrollTo 기능 변경 및 isWindow 함수 추가

feat(react): useScrollTo 기능 변경 및 isWindow 함수 추가

---

.changeset/early-turtles-visit.md
docs/docs/utils/string/serialize.md
packages/utils/src/string/index.ts
packages/utils/src/string/serialize/index.ts
packages/utils/src/string/serialize/internal.ts
packages/utils/src/string/serialize/serialize.spec.ts

Issue: #370 
객체로 들어온 값을 쿼리 파라미터로 사용할 수 있도록 직렬화해주는 유틸함수입니다.

feat(utils): serialize 유틸함수 추가 완료

---

.changeset/gold-cows-travel.md
docs/docs/react/hooks/useScrollTo.mdx
packages/react/src/hooks/useScrollTo/index.ts
packages/react/src/hooks/useScrollTo/internal.ts
packages/react/vitest.config.ts

fix(react): useScrollTo align 옵션 추가

---

.changeset/little-roses-itch.md
docs/docs/utils/validator/isNumericString.md
packages/utils/src/validator/index.ts
packages/utils/src/validator/isNumericString/index.ts
packages/utils/src/validator/isNumericString/isNumericString.spec.ts

feat(isNumericString): Add isNumericString

---

.changeset/calm-tigers-remember.md
docs/docs/utils/object/mapKeys.md
packages/utils/src/object/index.ts
packages/utils/src/object/mapKeys/index.ts
packages/utils/src/object/mapKeys/mapKeys.spec.ts

Issue: #321 
객체의 key를 iteratee의 결과 값 변환해주는 함수입니다.

feat(utils) mapKeys 유틸 함수 추가

---

packages/utils/src/object/mapKeys/mapKeys.spec.ts
packages/utils/vitest.config.ts

@Gaic4o test코드의 누락된 import를 추가합니다.
이제 테스트 코드에 테스트 관련 import문을 모두 추가해주도록 변경됐습니다. 

test: 누락 import 추가

---

docs/docs/utils/object/mapKeys.md
docs/docs/utils/object/mapValues.md
packages/utils/src/array/flattenDeep/index.ts
packages/utils/src/array/flattenDeepThenMap/index.ts
packages/utils/src/array/intersection/index.ts
packages/utils/src/object/mapKeys/index.ts
packages/utils/src/object/mapKeys/mapKeys.bench.ts
packages/utils/src/object/mapValues/index.ts
packages/utils/src/object/mapValues/mapValues.bench.ts
packages/utils/src/object/mapValues/mapValues.spec.ts

mapKeys, Values 로직 일부 수정 및 밴치마크

fix: mapKeys, Values 밴치 마크 테스트 추가

---

.changeset/tough-bananas-reflect.md
docs/docs/react/hooks/useCounter.mdx
packages/react/src/hooks/index.ts
packages/react/src/hooks/useCounter/index.ts
packages/react/src/hooks/useCounter/useCounter.spec.ts

Issue: #348 
feat(react): useCounter 함수 추가

feat(react): useCounter 함수 추가

---

.changeset/slimy-keys-camp.md
docs/docs/utils/array/flatMap.md
packages/react/src/hooks/useCounter/index.ts
packages/utils/src/array/chunk/index.ts
packages/utils/src/array/flatMap/flatMap.bench.ts
packages/utils/src/array/flatMap/flatMap.spec.ts
packages/utils/src/array/flatMap/index.ts
packages/utils/src/array/flatten/index.ts
packages/utils/src/array/flattenDeep/index.ts
packages/utils/src/array/flattenDeepThenMap/index.ts
packages/utils/src/array/index.ts
packages/utils/src/array/shuffle/index.ts
packages/utils/src/common/pickFalsy/index.ts
packages/utils/src/object/mergeProperties/index.ts
packages/utils/src/string/serialize/index.ts
packages/utils/src/validator/isEqual/isEqual.utils.ts

feat(utils): flatMap 신규 유틸 함수 추가

---

packages/react/rollup.config.mjs
packages/react/src/components/AspectRatio/AspectRatio.module.css
packages/react/src/components/AspectRatio/index.tsx
packages/react/src/css.d.ts
packages/react/src/global.d.ts
packages/react/tsconfig.json

fix: css.d.ts 추가

---

.changeset/healthy-dolphins-flow.md
docs/docs/utils/array/compact.md
packages/utils/src/array/compact/compact.spec.ts
packages/utils/src/array/compact/index.ts
packages/utils/src/array/index.ts

falsy한 값(0, '', null, NaN, undefined)을 모두 제거하는 배열입니다!
Issue: #399 

feat(utils): compact 유틸 함수 추가

---

docs/docs/utils/array/compact.md
packages/utils/src/array/compact/compact.bench.ts
packages/utils/src/validator/isArray/index.ts
packages/utils/src/validator/isBoolean/index.ts
packages/utils/src/validator/isFloat/index.ts
packages/utils/src/validator/isFunction/index.ts
packages/utils/src/validator/isInRange/index.ts
packages/utils/src/validator/isNumber/index.ts
packages/utils/src/validator/isNumericString/index.ts
packages/utils/src/validator/isPlainObject/index.ts
packages/utils/src/validator/isPrimitive/index.ts
packages/utils/src/validator/isPromise/index.ts
packages/utils/src/validator/isReference/index.ts
packages/utils/src/validator/isString/index.ts
packages/utils/src/validator/isSubset/index.ts

utils validator 일부 모듈 ts-doc 추가

---

packages/utils/src/array/intersection/index.ts
packages/utils/src/array/intersectionWithDuplicates/index.ts

docs(utils): Intersection ts-doc 추가

docs(utils): Intersection ts-doc 추가

---

.changeset/wicked-snakes-repair.md
docs/docs/react/hooks/useDebouncedInputValue.mdx
packages/react/src/hooks/index.ts
packages/react/src/hooks/useDebounce/index.ts
packages/react/src/hooks/useDebouncedInputValue/index.ts
packages/react/src/hooks/useDebouncedInputValue/useDebouncedInputValue.spec.ts
packages/react/src/utils/test/mockIntersectionObserver.ts
packages/react/vitest.setup.ts
packages/utils/src/array/intersection/index.ts
packages/utils/src/array/intersectionWithDuplicates/index.ts

Issue: #371 
feat(react): useDebouncedInputValue 신규 훅 추가

feat(react): useDebouncedInputValue 신규 훅 추가

---

.changeset/tall-jeans-divide.md
docs/docs/utils/common/hexToRgba.md
docs/docs/utils/common/once.md
packages/utils/src/common/asyncNoop/index.ts
packages/utils/src/common/delay/index.ts
packages/utils/src/common/hexToRgba/hexToRgba.spec.ts
packages/utils/src/common/hexToRgba/index.ts
packages/utils/src/common/hexToRgba/utils.ts
packages/utils/src/common/index.ts
packages/utils/src/common/noop/index.ts
packages/utils/src/common/once/index.ts
packages/utils/src/common/once/once.spec.ts

feat(utils): once 함수 추가

---

.changeset/sharp-bananas-prove.md
docs/docs/react/hooks/useInterval.mdx
docs/docs/react/hooks/useLocalStorage.mdx
docs/docs/react/hooks/useSessionStorage.mdx
docs/docs/react/hooks/useTimeout.mdx
packages/react/src/_internal/storage.ts
packages/react/src/hooks/useInterval/index.ts
packages/react/src/hooks/useInterval/useInterval.spec.tsx
packages/react/src/hooks/useInterval/useInterval.types.ts
packages/react/src/hooks/useInterval/useInterval.utils.ts
packages/react/src/hooks/useLocalStorage/index.ts
packages/react/src/hooks/useLocalStorage/useLocalStorage.utils.ts
packages/react/src/hooks/useSessionStorage/index.ts
packages/react/src/hooks/useSessionStorage/useSessionStorage.utils.ts
packages/react/src/hooks/useTimeout/index.ts
packages/react/src/hooks/useTimeout/useTimeout.types.ts
packages/react/src/hooks/useTimeout/useTimeout.utils.ts

fix(react): useInterval, useTimeout 개선

fix(react): useInterval, useTimeout 개선

---

.changeset/twelve-elephants-study.md
docs/docs/utils/array/drop.md
docs/docs/utils/array/fill.md
packages/utils/src/array/drop/drop.bench.ts
packages/utils/src/array/drop/drop.spec.ts
packages/utils/src/array/drop/index.ts
packages/utils/src/array/index.ts

Issue: #437 
배열의 첫 요소부터 n개의 요소가 삭제된 새로운 배열을 반환합니다.

feat: drop 유틸함수 추가

---

packages/react/src/hooks/useClipboard/index.ts

fix: 불 필요한 err 제거

---

.changeset/purple-singers-teach.md
docs/docs/react/hooks/useCycleList.mdx
docs/docs/react/hooks/useDebounce.mdx
docs/docs/react/hooks/useDebouncedInputValue.mdx
docs/docs/react/hooks/useDebouncedState.mdx
docs/docs/react/hooks/useStep.mdx
packages/react/src/hooks/index.ts
packages/react/src/hooks/useCycleList/index.ts
packages/react/src/hooks/useDebounce/index.ts
packages/react/src/hooks/useDebouncedInputValue/index.ts
packages/react/src/hooks/useDebouncedState/index.ts
packages/react/src/hooks/useDebouncedState/useDebouncedState.spec.tsx
packages/react/src/hooks/useStep/index.ts

feat: useDebouncedState 신규 훅 추가

feat: useDebouncedState 신규 훅 추가

---

.changeset/loud-taxis-walk.md
docs/docs/react/hooks/useDebounce.mdx
docs/docs/react/hooks/usePreservedCallback.mdx
docs/docs/react/hooks/usePreservedState.mdx
docs/docs/react/hooks/useThrottle.mdx
docs/docs/react/hooks/useToggle.mdx
packages/react/src/hooks/index.ts
packages/react/src/hooks/usePreservedCallback/index.ts
packages/react/src/hooks/usePreservedState/index.ts
packages/react/src/hooks/useResizeObserver/index.ts
packages/react/src/hooks/useThrottle/index.ts
packages/react/src/hooks/useThrottle/useThrottle.spec.ts
packages/react/src/hooks/useToggle/index.ts
packages/react/src/hooks/useToggle/useToggle.spec.tsx

feat(react): useThrottle 훅 추가

---

.github/workflows/codecov.yml

chore: workflows codecov 수정

---

docs/docs/react/hooks/useEventListener.mdx
docs/docs/react/hooks/useKeyDown.mdx
docs/docs/react/hooks/useMediaQuery.mdx
docs/docs/react/hooks/useMouse.mdx
docs/docs/react/hooks/useOutsidePointerDown.mdx
docs/docs/react/hooks/usePreservedCallback.mdx
docs/docs/react/hooks/useVisibilityChange.mdx
docs/docs/react/hooks/useWindowSize.mdx
packages/react/src/hooks/useEventListener/index.ts
packages/react/src/hooks/useKeyDown/index.ts
packages/react/src/hooks/useKeyDown/useKeydown.spec.tsx
packages/react/src/hooks/useWindowSize/index.ts

docs: 여러 훅 문서 및 ts-doc 추가

---

.changeset/good-books-carry.md
packages/utils/src/array/contains/index.ts
packages/utils/src/array/difference/index.ts

fix(utils): contains 타입 개선 및 ts-doc 작성

fix(utils): contains 타입 개선

---

.changeset/tiny-tomatoes-deliver.md
docs/docs/utils/array/at.md
packages/utils/src/array/at/at.bench.ts
packages/utils/src/array/at/at.spec.ts
packages/utils/src/array/at/index.ts
packages/utils/src/array/index.ts

feat(utils): at 신규 함수 추가

---

.changeset/curly-pants-notice.md
docs/docs/react/hooks/useUserAgent.mdx
packages/react/src/hooks/useUserAgent/index.ts
packages/react/src/hooks/useUserAgent/useUserAgent.spec.ts

fix(react): useUserAgent 개선

---

.changeset/old-experts-begin.md
packages/react/src/hooks/useHover/index.ts
packages/react/src/hooks/useUserAgent/index.ts
packages/react/src/hooks/useUserAgent/useUserAgent.spec.ts

fix(react): useUserAgent, useHover 수정

---

.changeset/itchy-papayas-reply.md
docs/docs/utils/object/findKey.md
packages/utils/src/object/findKey/findKey.bench.ts
packages/utils/src/object/findKey/findKey.spec.ts
packages/utils/src/object/findKey/index.ts
packages/utils/src/object/index.ts

Issue: #449 
객체에서 조건에 부합하는 key를 반환해주는 함수입니다.

feat(utils): findKey 함수 추가

---

.changeset/kind-mirrors-dance.md
docs/docs/react/hooks/useKeyDown.mdx
packages/react/src/hooks/useHover/index.ts
packages/react/src/hooks/useKeyDown/index.ts
packages/react/src/hooks/useKeyDown/useKeyDown.utils.ts
packages/react/src/hooks/useKeyDown/useKeydown.spec.tsx
packages/react/src/hooks/useResizeObserver/index.ts

feat(react): useKeyDown 및 useResizeObserver 로직 개선

feat(react): useKeyDown 및 useResizeObserver 로직 개선

---

.changeset/blue-donkeys-camp.md
.changeset/fluffy-pets-double.md
docs/docs/react/hooks/useCycleList.mdx
packages/react/src/hooks/useCycleList/index.ts
packages/react/src/hooks/useCycleList/useCycleList.spec.ts
packages/react/src/hooks/useStep/index.ts
packages/utils/src/validator/isPlainObject/index.ts
packages/utils/src/validator/isPlainObject/isPlainObject.spec.ts

refac: useStep 리팩토링 및 ts-doc 추가 및 useCycleList 개선

---

packages/react/src/components/FallbackLazyImage/FallbackLazyImage.spec.tsx
packages/react/src/hooks/useAsyncProcessQueue/useAsyncProcessQueue.spec.ts
packages/react/src/hooks/useFocus/useFocus.spec.tsx
packages/react/src/hooks/useHover/useHover.spec.tsx

fix(react): vitest mock type issue fix

---

packages/react/src/hooks/useFocus/index.ts

docs(react): useFocus ts-doc 수정

---

packages/utils/src/validator/isEqual/isEqual.spec.ts
packages/utils/vitest.config.ts

test: vitest issue 해결

---

.changeset/blue-dogs-chew.md
packages/react/src/hooks/useNetwork/index.ts
packages/react/src/hooks/useNetwork/useNetwork.spec.tsx
packages/react/src/hooks/useStep/useStep.spec.ts

fix(react): useNetwork 스펙 변경 및 한글화

fix(react): useNetwork 스펙 변경 및 한글화

---

.changeset/eight-yaks-attend.md
docs/docs/react/hooks/useIntersectionObserver.mdx
packages/react/src/hooks/useIntersectionObserver/index.ts

fix(react): useIntersectionObserver 기능 개선

fix(react): useIntersectionObserver 기능 개선

---

.changeset/dull-insects-hug.md
docs/docs/react/components/Slot.mdx
packages/react/src/components/Slot/Slot.spec.tsx
packages/react/src/components/Slot/Slot.utils.ts
packages/react/src/components/Slot/index.tsx
packages/react/src/components/index.ts
packages/react/src/hooks/useMergeRefs/index.ts

feat(react): Slot 컴포넌트 추가
reference: https://www.radix-ui.com/primitives/docs/utilities/slot

feat(react): Slot 컴포넌트 추가

---

packages/react/src/components/Slot/Slot.spec.tsx
packages/react/src/components/Slot/index.tsx

fix: ts-doc

---

.changeset/moody-hats-think.md
docs/docs/utils/formatter/formatNumberWithCommas.md
docs/docs/utils/validator/isPromise.md
packages/utils/src/formatter/formatNumberWithCommas/formatNumberWithCommas.spec.ts
packages/utils/src/formatter/formatNumberWithCommas/index.ts
packages/utils/src/validator/isNumericString/isNumericString.spec.ts
packages/utils/src/validator/isPromise/index.ts
packages/utils/src/validator/isPromise/isPromise.spec.ts

fix(utils): formatNumberWithCommas 기능 개선 및 한글화

fix(utils): formatNumberWithCommas 기능 개선 및 한글화

---

packages/utils/src/array/difference/difference.spec.ts
packages/utils/src/array/difference/index.ts

docs: ts-dco 수정

---

packages/utils/src/common/identity/identity.spec.ts
packages/utils/src/common/identity/index.ts

docs(utils): identity 한글화

---

.changeset/great-ways-arrive.md
docs/docs/utils/object/findKey.md
docs/docs/utils/object/mapKeys.md
docs/docs/utils/object/mapValues.md
packages/utils/src/object/findKey/findKey.bench.ts
packages/utils/src/object/findKey/findKey.spec.ts
packages/utils/src/object/findKey/index.ts
packages/utils/src/object/mapKeys/index.ts
packages/utils/src/object/mapKeys/mapKeys.bench.ts
packages/utils/src/object/mapKeys/mapKeys.spec.ts
packages/utils/src/object/mapValues/index.ts
packages/utils/src/object/mapValues/mapValues.bench.ts
packages/utils/src/object/mapValues/mapValues.spec.ts

fix(utils): findKey 인터페이스 변경

---

.changeset/mighty-buckets-drum.md
docs/docs/react/components/AspectRatio.mdx
packages/react/src/components/AspectRatio/AspectRatio.spec.tsx
packages/react/src/components/AspectRatio/index.tsx

feat(react): AspectRatio Slot 적용

feat(react): AspectRatio Slot 적용

---

.changeset/green-dolls-jog.md
.changeset/lovely-seahorses-double.md
packages/react/package.json
yarn.lock

chore: lodash-es dependencies 설정

---

.changeset/cool-zoos-learn.md
packages/react/package.json

fix(react): @modern-kit/utils 의존성 위치 변경

fix(react): @modern-kit/utils 의존성 위치 변경

---

.changeset/polite-apes-rush.md
docs/docs/react/components/AspectRatio.mdx
packages/react/src/components/AspectRatio/index.tsx

fix(react): AspectRatio 인터페이스 및 내부 로직 개선

fix(react): AspectRatio 인터페이스 및 내부 로직 개선

---

packages/react/src/components/AspectRatio/AspectRatio.spec.tsx
packages/react/src/components/AspectRatio/index.tsx

test: aspectRatio 테스트 코드 수정

---

.changeset/blue-berries-itch.md
docs/docs/react/components/InView.mdx
packages/react/src/components/AspectRatio/index.tsx
packages/react/src/components/ClientGate/index.tsx
packages/react/src/components/InView/InView.spec.tsx
packages/react/src/components/InView/index.tsx

fix(react): 컴포넌트 InView Slot 적용 및 개선

fix(react): 컴포넌트 InView Slot 적용 및 개선

---

.changeset/blue-shoes-clean.md
docs/docs/react/components/InView.mdx
docs/docs/react/components/InfiniteScroll.mdx
packages/react/src/components/InView/index.tsx
packages/react/src/components/InfiniteScroll/InfinteScroll.spec.tsx
packages/react/src/components/InfiniteScroll/index.tsx
packages/react/src/components/index.ts
packages/react/src/hooks/useCounter/useCounter.spec.ts

무한 스크롤 기능을 선언적으로 사용 할 수 있는 InfiniteScroll을 추가합니다.
단순한 유틸 기능만을 제공하고, 그 외 ref/스타일은 외부 사용자에게 책임을 위임합니다.

feat(react): InfiniteScroll 컴포넌트 추가

---

.changeset/blue-berries-itch.md

chore: changeset log 수정

---

.changeset/pretty-windows-sort.md
docs/docs/react/components/AspectRatio.mdx
docs/docs/react/components/InView.mdx
docs/docs/react/components/Slot.mdx
packages/react/package.json
packages/react/src/components/AspectRatio/AspectRatio.modules.css
packages/react/src/components/AspectRatio/AspectRatio.spec.tsx
packages/react/src/components/AspectRatio/index.tsx
packages/react/src/components/InView/InView.spec.tsx
packages/react/src/components/InView/index.tsx
packages/react/src/components/Slot/index.tsx
packages/react/src/utils/polymorphicForwardRef.tsx

fix: AspectRatio Slot 및 polymorphicForwardRef 적용

fix: AspectRatio Slot 및 polymorphicForwardRef 활용을 통한 다형성 지원

---

docs/docs/react/components/AspectRatio.mdx
docs/docs/react/components/InView.mdx
packages/react/src/components/InView/index.tsx

docs: inView, AspectRation 컴포넌트 문서 수정

docs: inView, AspectRation 컴포넌트 문서 수정

---

packages/react/src/hooks/useStep/useStep.spec.ts

test: useStep ci/cd 테스트 실패 케이스 개선

test: useStep ci/cd 테스트 실패 케이스 개선

---

.changeset/shiny-insects-lay.md
docs/docs/utils/object/objectEntries.md
docs/docs/utils/object/objectKeys.md
docs/docs/utils/object/objectValues.md
packages/types/src/ObjectEntries/index.ts
packages/types/src/ObjectKeys/index.ts
packages/utils/package.json
packages/utils/src/object/objectEntries/index.ts
packages/utils/src/object/objectEntries/objectEntries.spec.ts
packages/utils/src/object/objectKeys/index.ts
packages/utils/src/object/objectKeys/objectKeys.spec.ts
packages/utils/src/object/objectValues/index.ts
packages/utils/src/object/objectValues/objectValues.spec.ts
yarn.lock

fix: objectKeys/Values/Entries 타입 수정 및 문서/ ts-doc 개선

fix: objectKeys/Values/Entries 타입 수정 및 문서/ ts-doc 개선

---

.changeset/friendly-mayflies-play.md

chore: changesetlog 추가

---

.changeset/rich-jobs-fry.md
docs/docs/utils/formatter/formatNumberWithCurrency.md
packages/utils/src/formatter/formatNumberWithCurrency/formatNumberWithCurrency.constants.ts
packages/utils/src/formatter/formatNumberWithCurrency/formatNumberWithCurrency.spec.ts
packages/utils/src/formatter/formatNumberWithCurrency/formatNumberWithCurrency.types.ts
packages/utils/src/formatter/formatNumberWithCurrency/formatNumberWithCurrency.utils.ts
packages/utils/src/formatter/formatNumberWithCurrency/index.ts
packages/utils/src/formatter/formatNumberWithUnits/formatNumberWithUnits.utils.ts
packages/utils/src/formatter/formatNumberWithUnits/index.ts

fix(utils): formatNumberWithCurrency locale 값 타입을 locale 포맷에 맞게 변경

fix(utils): formatNumberWithCurrency locale 값 타입을 locale 포맷에 맞게 변경

---

docs/docs/utils/formatter/formatNumberWithCurrency.md
packages/utils/src/formatter/formatNumberWithCurrency/formatNumberWithCurrency.spec.ts
packages/utils/src/formatter/formatNumberWithCurrency/formatNumberWithCurrency.types.ts
packages/utils/src/formatter/formatNumberWithCurrency/formatNumberWithCurrency.utils.ts
packages/utils/src/formatter/formatNumberWithCurrency/index.ts

fix(utils): formatNumberWithCurrency decimal 옵션 제거

fix(utils): formatNumberWithCurrency decimal 옵션 제거

---

.changeset/rude-frogs-do.md
packages/react/package.json
yarn.lock

chore: package.json dependencies 수정

chore: package.json dependencies 수정

---

.changeset/smart-weeks-kiss.md
packages/react/build.utils.mjs
packages/react/package.json

fix(react): package.json 및 build utils 변경

fix(react): package.json 및 build utils 변경

---

.changeset/strange-vans-double.md
packages/react/rollup.config.mjs
packages/react/src/components/LazyImage/index.tsx

fix(react): rollup setting 수정

---

.changeset/spotty-bananas-shave.md
docs/docs/react/components/AspectRatio.mdx
packages/react/package.json
packages/react/rollup.config.mjs

chore: dist exports 추가

---

packages/utils/src/validator/isMIMEType/index.ts
packages/utils/src/validator/isMIMEType/isMIMEType.spec.ts

fix: typecheck 수정

---

.changeset/slimy-games-tap.md
packages/react/build.utils.mjs
packages/react/package.json
packages/react/rollup.config.mjs
packages/react/subPaths.mjs

chore: @modern-kit/utils SubPath 제공

chore: @modern-kit/utils SubPath 제공

---

yarn.lock

chore: yarn.lock 최신화

---

packages/react/package.json
packages/utils/rollup.config.mjs
yarn.lock

chore: rollup external 추가

---

packages/react/build.utils.mjs
packages/utils/build.utils.mjs

chore: react/utils build setting update

chore: react/utils build setting update

---

.changeset/hot-rabbits-matter.md
docs/docs/react/components/ClientGate.mdx
docs/docs/react/components/IfElse.mdx
docs/docs/react/components/When.mdx
packages/react/src/components/ClientGate/index.tsx
packages/react/src/components/IfElse/IfElse.spec.tsx
packages/react/src/components/IfElse/index.tsx
packages/react/src/components/Mounted/index.tsx
packages/react/src/components/When/When.spec.tsx
packages/react/src/components/When/index.tsx

fix(react): ClientGate, IfElse, When, Mounted 인터페이스 개선 및 한글화

fix(react): ClientGate, IfElse, When, Mounted 인터페이스 수정 및 한글화

---

.changeset/dry-tips-fold.md
docs/docs/react/components/AspectRatio.mdx
docs/docs/react/components/Delay.mdx
packages/react/src/components/Delay/Delay.spec.tsx
packages/react/src/components/Delay/index.tsx
packages/react/src/components/index.ts
packages/react/src/hooks/useTimeout/index.ts
packages/react/src/hooks/useTimeout/useTimeout.spec.tsx
packages/react/subPaths.mjs
packages/utils/src/validator/isValidEmail/index.ts

지정된 시간이 지난 후에 자식 컴포넌트를 렌더링하는 컴포넌트입니다.
지연 시간 동안에는 fallback 컴포넌트가 렌더링됩니다.
```tsx
<Delay delay={1000} fallback={<Fallback />}>
<Component />
</Delay>
```

feat(react): Delay 컴포넌트 추가

---

docs/docs/react/hooks/useIntersectionObserver.mdx
docs/src/pages/index.tsx

docs: useIntersectionObserver 문서 수정

docs: useIntersectionObserver 문서 수정

---

packages/react/package.json
packages/types/package.json
packages/utils/package.json

chore: package.json detail 정보 추가

chore: package.json detail 정보 추가

---

docs/docs/utils/formatter/formatNumberWithCommas.md
packages/utils/src/date/isDateInRange/index.ts
packages/utils/src/date/isDateInRange/isDateInRange.spec.ts
packages/utils/src/formatter/formatNumberWithCommas/formatNumberWithCommas.spec.ts
packages/utils/src/formatter/formatNumberWithCommas/index.ts

fix: formatNumberWithCommas 로직 일부 수정

fix: formatNumberWithCommas 로직 일부 수정

---

packages/react/build.utils.mjs
packages/utils/build.utils.mjs

fix: scanDirectory 개선

---

docs/docs/react/components/EventExtender.mdx
packages/react/src/components/EventExtender/EventExtender.spec.tsx
packages/react/src/components/EventExtender/index.tsx

fix: EventExtender 컴포넌트 shouldAwait props 추가

---

.changeset/thirty-pots-sell.md
docs/docs/utils/object/objectEntries.md
docs/docs/utils/object/objectKeys.md
docs/docs/utils/object/objectValues.md
docs/docs/utils/string/countSubstringOccurrences.md
docs/docs/utils/string/extractLetters.md
docs/docs/utils/string/extractNumber.md
docs/docs/utils/string/removeLetters.md
docs/docs/utils/string/removeSpecialCharacters.md
docs/docs/utils/string/reverseString.md
packages/utils/src/object/objectKeys/index.ts
packages/utils/src/string/countSubstringOccurrences/countSubstringOccurrences.spec.ts
packages/utils/src/string/countSubstringOccurrences/index.ts
packages/utils/src/string/countSubstringOccurrences/internal.ts
packages/utils/src/string/extractLetters/extractLetters.spec.ts
packages/utils/src/string/extractLetters/index.ts
packages/utils/src/string/extractNumber/extractNumber.spec.ts
packages/utils/src/string/extractNumber/index.ts
packages/utils/src/string/index.ts
packages/utils/src/string/removeLetters/index.ts
packages/utils/src/string/removeLetters/removeLetters.spec.ts
packages/utils/src/string/removeSpecialCharacters/index.ts
packages/utils/src/string/removeSpecialCharacters/removeSpecialCharacters.spec.ts
packages/utils/src/string/reverseString/index.ts
packages/utils/src/string/trim/index.ts

removeLetters를 추가하고, 일부 코드 리팩토링 및 문서 개선
- 주어진 문자열에서 특정 옵션에 따라 문자를 제거하는 함수입니다.
```ts
// 문자를 제거
removeLetters('abc123!@#', { letters: true }); // '123!@#'
// 숫자를 제거
removeLetters('abc123!@#', { numbers: true }); // 'abc!@#'
// 문자와 숫자를 제거
removeLetters('abc123!@#', { letters: true, numbers: true }); // '!@#'
// 공백과 숫자를 제거
removeLetters('abc  123 !@#', { whiteSpace: true, numbers: true }); // 'abc!@#'
```

feat(utils): removeLetters 추가

---

docs/docs/react/components/DebounceHandler.mdx
docs/docs/react/components/Delay.mdx
docs/docs/react/components/FallbackLazyImage.mdx
docs/docs/react/hooks/useCounter.mdx
docs/docs/react/hooks/useCycleList.mdx
docs/docs/react/hooks/useDebouncedState.mdx
docs/docs/react/hooks/useFileReader.mdx
docs/docs/react/hooks/usePreferredColorScheme.mdx
docs/docs/react/hooks/useScrollLock.mdx
docs/docs/react/hooks/useThrottle.mdx

Issue: 
문서에 가독성 향상 및 혼란 방지를 위해 일부 오타를 수정했습니다. 

docs: Fix typos in react documentation 

---

.changeset/clever-apes-accept.md
docs/docs/utils/validator/isRegExp.md
packages/utils/src/validator/index.ts
packages/utils/src/validator/isRegExp/index.ts
packages/utils/src/validator/isRegExp/isRegExp.spec.ts

Issue: 
#779 
```ts
export function isRegExp(value: unknown): value is RegExp {
return value instanceof RegExp;
}
```

feat(utils): isRegExp 유틸 함수 추가

---

packages/utils/src/array/at/at.spec.ts
packages/utils/src/array/chunk/chunk.spec.ts
packages/utils/src/array/compact/compact.spec.ts
packages/utils/src/array/contains/contains.spec.ts
packages/utils/src/array/countOccurrencesInArray/countOccurrencesInArray.spec.ts
packages/utils/src/array/forEachRight/forEachRight.spec.ts
packages/utils/src/array/mapRight/mapRight.spec.ts
packages/utils/src/array/partition/partition.spec.ts
packages/utils/src/array/shuffle/shuffle.spec.ts
packages/utils/src/array/swap/swap.spec.ts
packages/utils/src/array/take/take.spec.ts
packages/utils/src/array/xor/xor.spec.ts

test: util 함수에 대한 테스트 코드 설명을 한글화

---

.changeset/young-pigs-kneel.md
docs/docs/utils/validator/isMap.md
packages/utils/src/validator/index.ts
packages/utils/src/validator/isMap/index.ts
packages/utils/src/validator/isMap/isMap.spec.ts

Issue: 
#576 
```ts
export function isMap<K, V>(value: unknown): value is Map<K, V> {
return value instanceof Map;
}
```

feat(utils): isMap 유틸 함수 추가

---

.changeset/cool-pets-beg.md
docs/docs/utils/common/invariant.md
docs/docs/utils/validator/isSet.md
packages/utils/src/common/index.ts
packages/utils/src/common/invariant/index.ts
packages/utils/src/common/invariant/invariant.spec.ts
packages/utils/src/validator/isSet/index.ts

feat(utils): invariant 신규 유틸 함수 추가
(작업중)

feat(utils): invariant 신규 유틸 함수 추가

---

.changeset/blue-swans-return.md
docs/docs/utils/math/sum.md
packages/react/src/hooks/useEventListener/index.ts
packages/react/src/hooks/useEventListener/useEventListener.utils.ts
packages/react/src/hooks/useIntersectionObserver/index.ts
packages/react/src/hooks/useMediaQuery/index.ts
packages/react/src/hooks/useMouse/index.ts
packages/react/src/hooks/useOutsidePointerDown/index.ts
packages/react/src/hooks/useToggleState/useToggleState.spec.ts
packages/react/src/hooks/useVisibilityChange/index.ts
packages/react/src/hooks/useWindowSize/index.ts
packages/utils/src/array/flatMap/index.ts
packages/utils/src/array/flatten/index.ts
packages/utils/src/math/range/index.ts
packages/utils/src/math/sum/index.ts
packages/utils/src/math/sum/sum.bench.ts
packages/utils/src/validator/isReference/index.ts
packages/utils/src/validator/isWindow/index.ts

fix(utils): flat, range, isReference 타입 개선

fix(utils): flatMap, range, isReference 타입 개선

---

docs/docs/react/hooks/useEventListener.mdx
docs/docs/react/hooks/useScrollTo.mdx
packages/react/src/hooks/useImageStatus/index.ts
packages/react/src/hooks/useScrollTo/index.ts

refac: useScrollTo 리팩토링

---

packages/react/src/components/SeparatedIterator/SeparatedIterator.spec.tsx
packages/react/src/components/SeparatedIterator/index.tsx

fix: Iterator 컴포넌트 테스트 코드 수정

---

packages/react/src/hooks/useMediaQuery/useMediaQuery.spec.tsx

test: 테스트 실패 수정

---

.changeset/plain-showers-sip.md
docs/docs/react/hooks/useInputState.mdx
packages/react/src/hooks/index.ts
packages/react/src/hooks/useInputState/index.ts
packages/react/src/hooks/useInputState/useInputState.spec.tsx

Issue: #802 
```tsx title="typescript"
//초기값 없음
import { useInputState } from '@modern-kit/react';
const Example = () => {
const { value, onChange, reset } = useInputState<string>();
return (
<>
<h1>{value}</h1>
<input type="text" name="test" onChange={onChange} value={value} />
<button onClick={reset}>reset</button>
</>
);
};
```
```tsx title="typescript"
//문자열 초기값
import { useInputState } from '@modern-kit/react';
const Example = () => {
const { value, onChange, reset } = useInputState<string>('testValue');
return (
<>
<h1>{value}</h1>
<input type="text" name="test" onChange={onChange} value={value} />
<button onClick={reset}>reset</button>
</>
);
};
```
```tsx title="typescript"
//객체 초기값
import { useInputState } from '@modern-kit/react';
const Example = () => {
const { value, onChange, …
```

feat(react): useInputState hook 추가

---

docs/docs/react/hooks/useInputState.mdx
packages/react/src/hooks/useInputState/index.ts

docs: useInputState 문서 수정

---

.changeset/all-cameras-doubt.md
.changeset/smooth-tools-shout.md
.changeset/sweet-jokes-jog.md
docs/docs/utils/math/percentage.md
docs/docs/utils/math/subtract.md
packages/types/src/DeepPartial/index.ts
packages/types/src/DeepRequired/DeepRequired.spec.ts
packages/types/src/DeepRequired/index.ts
packages/types/src/index.ts
packages/utils/src/date/getDDay/getDDay.spec.ts
packages/utils/src/math/index.ts
packages/utils/src/math/percentage/index.ts
packages/utils/src/math/percentage/percentage.spec.ts
packages/utils/src/math/subtract/index.ts
packages/utils/src/math/subtract/subtract.spec.ts

feat(utils): subtract/percentage 함수 추가

feat(utils): subtract/percentage 함수 추가

---

packages/react/src/hooks/useDependencyTimeout/index.ts

fix: useDependencyTimeout 수정

---

.changeset/curvy-bananas-deny.md
.changeset/soft-parents-jam.md
docs/docs/react/hooks/useDebouncedInputValue.mdx
packages/react/src/hooks/useDebouncedInputValue/index.ts
packages/react/src/hooks/useDebouncedInputValue/useDebouncedInputValue.spec.tsx

fix(react): Add useDebouncedInputValue initialValue

---

packages/react/src/hooks/useKeyDown/index.ts
packages/react/src/hooks/useKeyDown/useKeydown.spec.tsx

test: useKeydown typecheck

---

.changeset/forty-banks-fold.md

chore(react): 누락된 changesetlog 추가 및 배포

---

packages/react/src/components/InView/index.tsx
packages/react/src/components/Slot/index.tsx
packages/react/src/hooks/useMergeRefs/index.ts

fix: slot mergeRefs 이슈 해결

---

.changeset/four-hairs-chew.md
packages/utils/src/array/at/index.ts

docs(utils): at 주석 수정

---

.changeset/eight-hands-drop.md
packages/react/src/hooks/useStateWithHistory/index.ts

fix: useStateWithHistory 의존성 배열 수정

---

packages/react/src/hooks/useThrottle/index.ts
packages/react/src/hooks/useWindowSize/index.ts
packages/utils/src/common/throttle/index.ts

fix(react): useWindowSize 타입 에러 수정

fix(react): useWindowSize 타입 에러 수정

---

packages/utils/src/common/debounce/debounce.spec.ts
packages/utils/src/common/debounce/index.ts
packages/utils/src/common/throttle/throttle.spec.ts

test: debounce/throttle 테스트 코드 및 주석 개선

test: debounce/throttle 테스트 코드 및 주석 개선

---

packages/react/src/hooks/useThrottle/index.ts
packages/utils/src/common/debounce/debounce.spec.ts
packages/utils/src/common/throttle/throttle.spec.ts

test: debounce/throttle 테스트 코드 개선

test: debounce/throttle 테스트 코드 개선

---

packages/react/src/hooks/useThrottle/index.ts
packages/utils/src/common/debounce/debounce.spec.ts

test(debounce): 테스트 코드 개선

---

.changeset/public-ads-drum.md
docs/docs/react/hooks/useLocalStorage.mdx
packages/react/src/hooks/useLocalStorage/index.ts
packages/react/src/hooks/useLocalStorage/useLocalStorage.spec.tsx

feat(react): useLocalStorage visibilityChange 옵션 추가

feat(react): useLocalStorage visibilityChange 옵션 추가

---

.changeset/slimy-radios-stop.md
docs/docs/react/hooks/useControllableState.mdx
packages/react/src/hooks/index.ts
packages/react/src/hooks/useControllableState/index.ts
packages/react/src/hooks/useControllableState/useControllableState.spec.tsx

feat(react): useControllableState 신규 훅 추가

feat(react): useControllableState 신규 훅 추가

---

.changeset/afraid-ties-kick.md
docs/docs/utils/object/get.md
docs/docs/utils/object/set.md
packages/utils/src/object/get/index.ts
packages/utils/src/object/index.ts
packages/utils/src/object/set/index.ts
packages/utils/src/object/set/set.spec.ts

feat(utils): set 신규 함수 추가

---

.changeset/fancy-bags-lick.md
docs/docs/react/hooks/useControllableState.mdx
packages/react/src/hooks/useControllableState/index.ts

fix(react): useControllableState 타입 수정

fix(react): useControllableState 타입 수정

---

docs/docs/utils/storage/storageManager.md
packages/utils/src/storage/storageManager/index.ts
packages/utils/src/storage/storageManager/storageManager.spec.ts

feat(utils): StorageManager own 함수 추가

feat(utils): StorageManager own 함수 추가

---

.changeset/odd-phones-agree.md
docs/docs/react/hooks/useIdle.mdx
packages/react/src/hooks/index.ts
packages/react/src/hooks/useIdle/index.ts
packages/react/src/hooks/useIdle/useIdle.spec.ts

feat(react): useIdle 신규 훅 추가

---

docs/docs/react/hooks/useIdle.mdx
packages/react/src/hooks/useIdle/index.ts
packages/react/src/hooks/useIdle/useIdle.spec.ts

fix(react): useIdle throttle trailing false 적용

fix(react): useIdle throttle trailing false 적용
